### ISSUE TITLE
AppleScript API Request: server addresses

### ISSUE THREAD

**Issue by katerlouis** [bdkjones/CodeKit#195]
For my Alfred-workflow I would like to get the current server addresses.
Quickly to clipboard-history, printing it out with Alfred in big fat letters; send it instantly to open Slack-Chat; you know, such things.

(I don't dare to ask for a function that gives me a JSON-list with all the projects CodeKit knows)

**Comment by bdkjones** [comment]
Is a JSON list actually useful in AppleScript? I looked into that, but it seems like working with JSON in AppleScript is a giant pain.

**Comment by katerlouis** [comment]
Alfred works with JSON lists. But I see your point. Then I have to convert it myself.

**Comment by bdkjones** [comment]
Implemented for 3.8.

Decided to drop the JSON stuff and just return one address at a time since that's probably what you're looking for. It works like this:

    tell application "CodeKit" to get preview server url

That'll return whichever Preview Address you've set as the default for the app. 

And you can use the same `addressType` specifiers that already exist to get a specific one:

    tell application "CodeKit" to get preview server url using LAN address
