### ISSUE TITLE
Compile Sass to source and build folder

### ISSUE THREAD

**Issue by aerni90** [bdkjones/CodeKit#235]
I love the new possibility of the build folders workflow. However right now it is pretty useless to me, as Sass files only compile into the /build folder. 

Imagine this: You're working on index.html in the /source folder. You add a class to a div and specify the class in the /source/scss/main.scss file. Upon save, the index.html and main.scss files compile into the /build folder. So far so good. The problem here is, that the index.html in the /source folder doesn't get access to the compiled main.css as it is compiled into the /build/scss folder.

It would be great to have an option to compile Sass into the /source folder and then copy it to the /build folder.

**Comment by rvola** [comment]
Hi Aerni, 

check this video for more help : https://www.youtube.com/watch?v=FGyVTyNChzc

**Comment by aerni90** [comment]
Hi,

Yes, I checked it out and get how it works. However it doesn't solve the problem I'm running into.

**Comment by bdkjones** [comment]
`index.html` in the `source` folder does not NEED access to the CSS file. You're never going to use or look at `index.html` under the source folder. When you use build folders in CodeKit, your `build` folder automatically becomes the document root of your site. All files are previewed from there and, when you deploy your site, you deploy only the files in `build`.

**Comment by bdkjones** [comment]
The proposed idea (to compile a Sass file to a CSS file in the source folder and then copy the CSS file to the build folder) is a violation of the build folder workflow. This is just a matter of getting used to working with build folders instead of compiling files in place.

**Comment by bdkjones** [comment]
A common misconception with people new to "build" workflows is that your website should work *before* being built. That is, you should be able to view it in the source folder and everything should work correctly. That's not the case. When you use build folders, you MUST build the project and view it from the build folder---it's like developing an application. Your source folder is the source code of the app; it must be compiled (built) before it's useful.

**Comment by zmip** [comment]
Looking at your video, and noticing in CodeKit that you can't really change the build folder to something useful (like a relative path), it seems to me that you have quite a few assumptions on how people structure their source and output paths. The video shows the strangest workflow, where source and output (build) files are all mixed together. Super weird, from a developer standpoint. I'd love to use the "Build folder" functionality to output to my local dev webroot (which is never under "/build"... duh), which is in a completely different place than where my source files are, obviously (I mean, to me). Why not have us set the build folder *path* (not just a prefix), and mirror our (compiled) sources there? Perhaps I'm missing something here, but I'm using CodeKit merely to process some client-side technologies (sass, js, svg). The projects themselves involve way more than this, hence "a project" is not something I'm adding to CodeKit. Just the client-side source files please.

**Comment by bdkjones** [comment]
You can set a path in the build folder name field and that path is always relative to the project root folder.

The reason you can’t go ABOVE the project root folder is because CodeKit is used by about 100,000 people and some of them are...challenged. A guy once deleted his entire Documents folder because he put the wrong path in that field and CodeKit dutifully erased the “build folder.” It’s a safety feature—projects are always self-contained units.

**Comment by zmip** [comment]
I see your point. But dumbing down your application is not the right solution IMO. The way many apps that offer potentially dangerous functionality handle this, is to "hide" it from your "mentally challenged" users, but make it available to the rest of us. We don't mind going into a config file (the project file looks editable, but the warning at the top has stopped me for now (hey, that worked ;-)

I'm not using CodeKit because the CLI freaks me out. I just think CLI applications are stupid. So whenever there's a GUI-alternative, I'll use that. I mean, even XCode is not requiring you to build through the CLI, right? So CodeKit is a very elegant solution to using the offered processors/compilers from the command line. But IMHO, it should not impose limits that aren't there when using them from the CLI. It makes using the processors/compilers more elegant/insightful, but should be just as (if not: more) powerful. 

So Bryan, what are the chances that I can set the build folder path to my wishes when editing the config.codekit3 file? I'll just give it a go I guess ;-)

In case you're wondering how my projects are set up, let me illustrate that:

```
Project folder 1
Project folder 2
Project folder 3
- app folder <-- loads of application files, CodeKit should *not* touch, ever
- public_html folder <-- webroot, served through local webserver
-- index.php
-- assets folder
- dev folder (local development assets)
-- src assets folder
--- lib folder (e.g. Bootstrap)
--- src folder <-- this should be mirrored into the webroot under /assets
---- scss folder
---- svg folder
---- js folder

```

As you can imagine, dragging "Project folder 3" into CodeKit is not something I'd be happy to do, but this "build folder should be under the CodeKit root folder" would require me to do so. I'm definitely not going to. The "dev" folder also contains source artwork, project documents etc. Really stuff that CodeKit should not mess with.

**Comment by bdkjones** [comment]
Most of codekit has built-in safeguards against malformed config files. The setup you’ve described is pretty complex, but you can use the Skipped Items list in Project Settings > General to narrow down the folders that CodeKit indexes.
