### ISSUE TITLE
Shortcut Build - Feature request

### ISSUE THREAD

**Issue by rvola** [bdkjones/CodeKit#242]
As shortcut "Pause all watching" it would be cool to have a shortcut to build the project.

It can happened if you copy and rename the build folder file will be different from the source. With a keyboard shortcut that causes the build, the problem disappears.

**Comment by bdkjones** [comment]
Yea... I'm hesitant to add another global keyboard shortcut because they add a little overhead to the system and require another set of keys that are then unavailable for other apps.

Additionally, builds generally take some time and are intensive. They aren't something you want to do casually and frequently—you should build once at the start, then let CodeKit simply process files as they change. In your example, renaming a file/folder will trigger CodeKit to process the affected items (and only those items) automatically; there is no need for a full rebuild.

**Comment by rvola** [comment]
I agree not to have a permanent short cut.

Nevertheless, I think it would be possible to add the line "Build project" in the menus, in order to let people wishing to add a shortcut with Mac OS.

I need to rebuild a project, because if you duplicate a file, Codekit will copy it. If you rename the file (in the source), Codekit will not rename it ...

That's why I "force" a build

**Comment by heyfletch** [comment]
I agree that adding "Build Project" as a menu option is a great idea. I was looking for this, and couldn't find it. Therefore, it's sort of a user expectation that there is the option to build the project from the menu, and not just navigating around the UI to find the Build Project button, which can take some hunting / clicking. 

Also, this gives the user the option to do it, so why not?  

Finally, it also gives the user the ability to assign a MacOS keyboard shortcut if they so choose, and therefore improve the ability to not use the mouse.

**Comment by bdkjones** [comment]
I can definitely add a menu option, just not a global hotkey. And CodeKit should absolutely track and respond to file-renames. Unless you have file-watching paused or the folder is not in the app, CodeKit will rename files as you do in the Finder.
