### ISSUE TITLE
Clicking on href="javascript:void(0);" links refreshes the entire browser

### ISSUE THREAD

**Issue by clodal** [bdkjones/CodeKit#244]
**Quick, short summary:**
When on Codekit's preview address in the browser, whenever i click on a link with href = 'javascript:void(0);' or '#', the entire browser refreshes.

**Expected results:**
Clicking on these false href links results in no browser refresh because i want to open modals

**Actual results:**
Click on these href links loads my modal, but refreshes the entire page following that

**Exact steps to reproduce:**
Create a simple web page locally with an anchor element with href = 'javascript:void(0);' link, run it with codekit 3's preview address in your browser, click on the link, and watch the page refresh

**Your configuration (any details about your system that you think might be relevant)**
MacOs Sierra MAMP Pro + Codekit3 + Nginx + MySQL + PHP

Additional info: I've been running codekit 2 for the past few months. Clicking on these href false links did not refresh the entire page. Only noticed this issue after updating to codekit 3 today. Also,  if I run the browser address directly from MAMP, i don't get this issue.

**Comment by bdkjones** [comment]
Well that’s mystifying. I have no idea what’s causing that, but I’ll look into it today.

**Comment by bdkjones** [comment]
this *seems* like correct behavior off the bat. You're not canceling the click event with void(0). You'd need to use preventDefault() or return false, I believe. 

Clicking a link with an anchor tag (#) should not reload the page, but it will flash to the top of the page since no ID matches the specified anchor, if I remember correctly.

**Comment by bdkjones** [comment]
Yep. Confirmed. This problem is caused by your site. I put together an index.html page that looks like this: 

<img width="855" alt="screen shot 2016-11-03 at 15 48 50" src="https://cloud.githubusercontent.com/assets/926566/19988388/0869a1da-a1dd-11e6-80d5-d9deda246eef.png">

I then loaded it in my browser by clicking CodeKit's preview button. You can see the initial "page loaded" message in the console. I then clicked all three links a bunch. The page never reloaded, as expected:

![screen shot 2016-11-03 at 15 48 18](https://cloud.githubusercontent.com/assets/926566/19988413/2bb10bc4-a1dd-11e6-8947-4f74a3e1f813.png)

**Comment by bdkjones** [comment]
What *MAY* be happening is browserSync events are being mishandled somehow. Turn off browser sync in CodeKit's Preferences temporarily and see if that solves the issue.

**Comment by clodal** [comment]
Thanks for going through the trouble to make this prompt review. Seems like the bug went away after a reboot. Appreciate it!
