### ISSUE TITLE
Libsass compiler doesn't seem to support import globbing

### ISSUE THREAD

**Issue by avalanchedigital** [bdkjones/CodeKit#247]
Libsass compiler doesn't seem to support import globbing.  If there is no way around this then suggest noting it on:

https://codekitapp.com/help/sass/

**Comment by subhaze** [comment]
IIRC this is a ruby specific feature, because Ruby supports it.

**Comment by bdkjones** [comment]
Neither Ruby nor libsass support globbing automatically. It was rejected from the spec because it's a world of hurt. But I include the plugin for Ruby that allows it there. If i remember correctly, the libsass plugin was buggy, which is why I did not include it.

**Comment by KOchmeister** [comment]
What does it mean now? Is it a bug, that the globbing is not working or did you not include it? Because as avalanchedigita mentioned in the help area you say that with @import 'someFolder/*' it works... I have a lot of projects running with globbing. But since the new version the error log always tells me there is an error, but it still compiles the files.

**Comment by bdkjones** [comment]
Globbing is not currently available for Libsass. If you turn off Libsass for your Sass files, you can use the old Ruby compiler and globbing will work fine.

**Comment by bdkjones** [comment]
Looked again, but it doesn't seem there's a standalone plugin for globbing in Libsass that isn't dependent on Gulp or Grunt.
