### ISSUE TITLE
Bourbon 5 beta (why!?)

### ISSUE THREAD

**Issue by eaglejohn** [bdkjones/CodeKit#260]
I really like this app and I've been using it for years. I voluntarily paid the maximum amount possible for v2 and also for v3. But it's really a bold move to suddenly include the new (beta!!!) version of Bourbon. It results in many errors since a lot of mixins have been removed. Can't find any documentation on the Bourbon website how to fix/replace the mixins. There's nothing in their changelog, like you mentioned in your own changelog.

It's especially a problem for projects that need some small tweaks (that are not even related to those mixins!). Just recompiling my CSS results in so many errors. This is kinda unacceptable in my opinion, it takes a lot of time to fix it and when it has to be done in a live website it's very stressful and frustrating.

**Comment by bdkjones** [comment]
Well, the app has to move on at some point. Bourbon 5.0 Beta 7 is virtually final. The reason I moved to it is that the latest version of Bourbon Bitters requires Bourbon 5+.

Most of the changes in 5.0 involve removing mixins that aren't needed anymore. If you don't want to tweak your Sass, you can download Bourbon 4.x stylesheets and add them to your project rather than rely on the assets bundled into CodeKit.

The web world moves fast.
