### ISSUE TITLE
Folder rules (feature request)

### ISSUE THREAD

**Issue by JonathanDoelan** [bdkjones/CodeKit#266]
There is this option for a whole folder to be „ignored“ or „processed“ or „just copied“. It would be nice if such a folder could be marked visually as „only copy“ or „ignore“ … or … if I click on the folder, the „right panel“ could already show „Copy (Without Processing)“ instead of clicking on „set output actions“.

**Comment by bdkjones** [comment]
I'm afraid I don't understand the first part of this request. 

As for the latter (showing the output action rather than "set output actions") --- that exists for a good technical reason. The contents of the folder will almost always be mixed output actions, which means the field is blank. It's also not clear that by changing the dropdown you'd be affecting ALL items anywhere in or under that folder. I wanted a much more prominent "THIS IS GOING TO FUCK A LOT OF STUFF UP, ARE YOU SURE?" modal confirmation.
