### ISSUE TITLE
Edit name of build files (feature request)

### ISSUE THREAD

**Issue by JonathanDoelan** [bdkjones/CodeKit#267]
If I have a file example.scss and I want it to compile to the build folder with a **different name**, I have to select the full path to the build-folder. Would be nice to just have an option to only rename the file, without loosing the build-configuration (path).

**Comment by bdkjones** [comment]
Ok. I've changed the app so that when you click `change`, the sheet that pops up will now default to the output folder of the FIRST selected item in the files list. That way, you can simply change the name in the textfield at the bottom of that sheet and apply it.

Previously, the sheet defaulted to the project's root folder.
