### ISSUE TITLE
ESLint no-redeclare error, when using ES6 modules

### ISSUE THREAD

**Issue by hpohlmeyer** [bdkjones/CodeKit#269]
**Quick, short summary:**
When using ES6 Modules, ESLint throws a "module is allready defined (no-redeclare)" error, if one module is imported in multiple modules with the same path name.

Checking the same files manualy does not return an error.

**Expected results:**
CodeKit should throw the same report I get, when use ESLint from the CLI.

**Actual results:**
An error gets thrown.

**Exact steps to reproduce:**
1. Create a main file, a module file and a submodule file
2. Import the module file in the main file
3. Import the submodule in the main file and the module file (the syntax has to be the same)
4. Check the sytanx of the main file with CodeKit

**A link to download a simplified project or file that shows the issue:**
[module_test.zip](https://github.com/bdkjones/CodeKit/files/589072/module_test.zip)

**Example project instructions**
1. Terminal: cd to the project
2. Terminal: run `npm install`
3. CodeKit: open the project
4. CodeKit: check syntax of `main.js` (errors)
5. Terminal: run `node_modules/eslint/bin/eslint.js submodule.js module.js main.js` (no errors)

**Additional information**
I realized, that I don’t get an error, when I put my modules in a subfolder. I think the reason for that is, that the filepaths of the imports differ.

I also noticed, that CodeKit does not go up the whole import tree and only performs syntax checking on the direct import of the checked file. (In my project `submodule` never gets checked) But that may be a case for another bug report.

**Comment by bdkjones** [comment]
Okay, I think this has been solved by ESLint. I've been testing ESLint with the new bundling stuff in 3.8 and haven't hit this snag. I also see some discussion about similar problems in ESLint's old issues.

As for syntax-checking: the way that's working from 3.8 on is that CodeKit will walk the entire import tree and check every single file as well as all of its imports. Each import is checked in its own scope (since they should technically BE their own scope). If, however, you turn off linting for a given imported file, CodeKit will not descend into the tree past that file, so you'll turn off issues for file X **and** all files that X imports. (Unless those files are imported by some other file Y that DOES have linting turned on).

Circular imports should be properly handled. Isn't JavaScript great?
