### ISSUE TITLE
Computer crashes when sending dev URL via Messages

### ISSUE THREAD

**Issue by kmmathis** [bdkjones/CodeKit#273]
**Quick, short summary:**
When sending the CodeKit development URL via Messages, my computer completely crashes when Messages tries to create the page preview.

**Expected results:**
I should be able to send the dev URL via Messages without my computer crashing.

**Actual results:**
Messages has a problem generating the preview and crashes my computer. Also CodeKit recognizes that it crashed after the computer restarts but it can't find any error log files.

**Exact steps to reproduce:**
Run CodeKit with Browser Refreshing (using a MAMP host may or may not make a difference). Paste the development url into Messages and try sending to yourself or your mom or whomever.

**A link to download a simplified project or file that shows the issue:**
I think any project would have this issue

**Your configuration (any details about your system that you think might be relevant)**
OSX Sierra, running MAMP Pro 3.5.2, using WordPress 4.6.1 and the latest version of CodeKit.

**Comment by kmmathis** [comment]
For what it's worth, I can send the MAMP host URL via Messages just fine.

**Comment by bdkjones** [comment]
Does this happen with only the Bonjour preview address?

**Comment by martyf** [comment]
I've just sent myself all preview addresses with no problems - including the Bonjour one.

Sierra 10.12.1
MAMP Pro 4.0.6
CodeKit 3.0.3 25444

**Comment by kmmathis** [comment]
Interesting, I'll do some more testing with my specific project and see if it's something on my end. I'll close this for now and reopen if I figure something out.

**Comment by bdkjones** [comment]
I believe your affected by what I like to call, "Apple Engineers are getting dumber." There's a bug in MacOS since El Cap where, in some network environments, Bonjour addresses will crash the entire system. CodeKit itself is literally not capable of crashing macOS---it doesn't have the capability to do so because it doesn't run any code in Kernel space. When you open the Bonjour preview address, CodeKit tosses that request to macOS using an Apple API that says, "open this address in the System's default browser". It's one line of code. Somewhere in that networking call (apple's code) a crash occurs that kernel panics your Mac. It seems to affect folks using Apple routers more than others, but I've had reports from a couple of people not using Apple routers as well. If your router is ancient (or made by Apple) I'd recommend upgrading. Apple's routers are criminally awful compared to what you can get elsewhere. Short of that, there's nothing I can do to solve this issue. Apple Engineering needs to fix their networking stack. I'd be sure to file a bug report with them and include the kernel panic log.

**Comment by martyf** [comment]
That's interesting Bryan (and not news of how crap Apple's networking is)
FWIW, **not** using an Apple router here - Billion 7800NX.

**Comment by bdkjones** [comment]
Sigh. iOS autocorrected to "your" above and it's bugging the crap out of me. I can't find a way to edit it on the mobile site, so just take my word that I'm not dumb.

**Comment by bdkjones** [comment]
I'd try repeating the process on a different LAN. Starbucks, etc. Let me know what happens.

**Comment by martyf** [comment]
Hey um odd one... why can I edit your comments? Surely that's a permission glitch?

**Comment by bdkjones** [comment]
If you were part of the beta, you're a contributor on the repo.
