### ISSUE TITLE
Hidden projects should stay hidden when closing/reopening the app

### ISSUE THREAD

**Issue by dlewand691** [bdkjones/CodeKit#280]
**Quick, short summary:**
Have a group of projects that are completed but don't want to remove from Codekit. I've hidden them in the project list but when restarting the app, they are shown.

**Expected results:**
Would like them to stay hidden at all times until shown

**Actual results:**

**Exact steps to reproduce:**
+ Hide a project group
+ Quit Codekit
+ See hidden group shown

**A link to download a simplified project or file that shows the issue:**

**Your configuration (any details about your system that you think might be relevant)**

**Comment by bdkjones** [comment]
By "hidden", do you mean you've collapsed the group in the Projects OutlineView? If so, the better approach is to remove completed projects from the app entirely. They suck up resources, memory and processor cycles.

I'm not willing to default to hiding project groups because, from experience, I find that many people aren't really qualified to operate a computer and I REALLY don't like support emails. I can totally see the emails I'd get from people telling me that the app is broken because it's not showing their projects.
