### ISSUE TITLE
confusing error-log when optimizing already optimized images 

### ISSUE THREAD

**Issue by helloDanuk** [bdkjones/CodeKit#283]
**Quick, short summary:**
Having images in Codekit that were optimized (i.e. with imageoptim) before adding them to Codekit, gives an error-log in Codekit when trying to optimize them.

**Expected results:**
A log-info, that the image is already optimized and could not further been optimized or just nothing.

**Actual results:**
«…It may be corrupt or damaged. Try re-exporting it from your image editor.» The log-message is confusing. For my knowledge, the image is not corrupt or damaged! It could just not been more optimized. Perhaps the log-error appears, because optimized images in Codekit and imageoptim gives the same file sizes.

**Exact steps to reproduce:**
1. Download imageoptim.com
2. Optimize an image with imageoptim (with default settings)
3. Add this image to Codekit
4. Optimize it with Codekit

**A link to download a simplified project or file that shows the issue:**
<img width="631" alt="bildschirmfoto 2016-11-29 um 09 47 32" src="https://cloud.githubusercontent.com/assets/8265902/20703061/8c99d5c8-b61a-11e6-8709-85a12aff2411.png">

**Comment by bdkjones** [comment]
Well, the issue here is that I have no way of knowing when a file has already been optimized. That message above is displayed whenever the optimizer throws a "could not parse the file" error. It's a catch-call message designed to cover all failures. 

Please send me an example image that DOES work and the same image, after optimization with another tool, that fails. Maybe I can use those those to track down exactly what's happening here.

**Comment by bobhuf** [comment]
I've got the same issue. Here's a zip with two images, one that fails and one that doesn't: https://dl.dropboxusercontent.com/u/2177001/Archief.zip

**Comment by helloDanuk** [comment]
Here are three images:
- original
- optimized with imageoptim (fails if you try this in codekit)
- optimized with codekit

https://dl.dropboxusercontent.com/u/5904141/image-optimization.zip

**Comment by bdkjones** [comment]
This is fixed for the next update. See #328 for details. Thanks!
