### ISSUE TITLE
Feature Request: Minimize html

### ISSUE THREAD

**Issue by spenserwolz** [bdkjones/CodeKit#297]
I know this is doable by adding grunt or something similar but I'd love if it was built in natively. It could just compile down inside the /build folder, so that leaves the original easily editable.

**Comment by luxlogica** [comment]
Minifying HTML is a complex and tricky process, and the value of the minification is often dubious:

[Don't Bother Using HTML White-Space Removal](http://nadeausoftware.com/articles/2007/03/don_t_use_html_white_space_removal_speed_web_site)

The benefits of minification can be easily overshadowed by the benefits of good coding practices, and using server compression, as explained [in this StackOverflow answer](http://stackoverflow.com/questions/466437/minifying-html) by "Mr. Shiny and New":

> You have to be careful when removing stuff from HTML as it's a fragile language. Depending on how your pages are coded some of that whitespace might be more significant; also if you have CSS styles such as white-space: pre then you may need to keep the whitespace. Plus there are numerous browser bugs, etc, and basically every character in an HTML file might be there to satisfy some requirement or appease some browser.
>
>In my opinion your best bet is to design the pages well with CSS techniques (I was recently able to take an important page on the site I work for and reduce it's size by 50% just by recoding it using CSS instead of tables and nested style="..." attributes). Then, use GZip to reduce the size of your pages for browsers that understand gzip. This will save bandwidth while preserving the structure of the html.

There is a feature request - issue #346 - for the integration of HTML Tidy into CodeKit, but the purpose there is to use it for **linting** of the code, rather than minification.

**Comment by Bangkokian** [comment]
I'd love to see just the ability to strip HTML comments, and blocks of content that have been commented out.

**Comment by JayHoltslander** [comment]
> and the value of the minification is often dubious - @luxlogica 

Tell that to Google [who considers minification](https://developers.google.com/speed/docs/insights/MinifyResources) in their site tests.

**Comment by luxlogica** [comment]
Google likes pages that load faster. If you're considering optimising your webpage for SEO and better rankings, then there's much more effective ways of lowering your time-to-load, and more importantly, your time-to-interaction. Turning on gzip compression on your web server will usually increase your site's speed much more than HTMLMinifier would ever be able to do. But anything you do to your HTML is going to hardly have any effect on your page loading time, because what slows down most webpages **by far** is the IMAGES and VIDEOS on the page. In some of our sites, the loading time of images account for anything from 70% to 90% of the total loading time. So, using [lazyloading](https://www.sitepoint.com/five-techniques-lazy-load-images-website-performance/) techniques you can **dramatically** increase your site's time-to-interaction, and organically increase your search engine rankings, without having to touch anything in your HTML. 

Some good frontend frameworks - like [UIKit](https://getuikit.com) - have built-in lazy-loading libraries, which will even lazy-load responsive background images in your elements. Using frameworks with lazyloading techniques like this, we have been able to reduce initial page loading times from over 9 seconds, to under 2 - with no change to our HTML.

**Comment by Bangkokian** [comment]
Again... the need for stripping comments is a clerical one,  more than an SEO one.  Depending on your workflow you may have blocks of commented-out code or production notes in comments that you would rather not publicize or reveal.  

On the loading-time side of things:  The differences may or may not be noticeable. It depends what you have inlined / commented out. SVG graphics for example, can easily affect loading time.

**Comment by luxlogica** [comment]
@Bangkokian Indeed, the need for stripping out comments is being discussed in Issue #462, opened by you. The issue here is about **minimising HTML** - and whether it's needed, or important. 

Again, SVG is a different, separate matter, and CodeKit already provides us with ways to optimise SVG files. Also for CSS, and Javascript. All of these different types of files can be inlined into your code, if you so wish. And again, the overhead of inlining all of these files into your HTML pales in comparison with the overhead of images and videos on an average webpage.

**Comment by Bangkokian** [comment]
[Hangs head in shame]... thread confusion. Gotta clean up my inbox. @luxlogica, you are correct sir.

**Comment by bdkjones** [comment]
Implemented for 3.8. 

See https://github.com/bdkjones/CodeKit/issues/462#issuecomment-466314158
