### ISSUE TITLE
Disable cache-buster option

### ISSUE THREAD

**Issue by nickimola** [bdkjones/CodeKit#306]
Hi,

I've checked everywhere but couldn't find anywhere how to disable the cache-buster, however, in an old version of codekit, an option to disable it is mentioned.

> FIXED: The cache buster is now much smarter and will handle URLs with query strings and anchor tags correctly. There is also now an option to disable the cache-buster completely.

Is this still an option? if yes, do you know how can I disable it?

I have the feeling that, when I compile, I'm serving the cached version and not the new one, as sometimes I have to do a hard reset on the browser and clear the cache manually in order to see my latest changes and this slows my development down quite significantly.

I may be completely wrong, but I'd like to have your feedback on it.

Thanks

**Comment by bdkjones** [comment]
There is no longer an option to disable the cache buster on link and script tags. If you're using PHP or another dynamic language, make sure your external server has opcache disabled. CodeKit will do this for MAMP in the tasks menu. Otherwise, use your browser dev tools to disable caching completely while you work.
