### ISSUE TITLE
Bower / Package Components Install

### ISSUE THREAD

**Issue by garethjohnsdesign** [bdkjones/CodeKit#308]
When I install components via Codekit it often seems to download a whole bunch of other folders with it, this becomes a slight issue as I'm worried about deleting any folders as I imagine that the reason it installs other components is that some Bower components use them. Is there any way to work out dependencies.

Apologies if this is a bit of a confusing question, a bit tricky to word correctly.

**Comment by bdkjones** [comment]
Your assumption is correct. This is what package managers do: download 8,345 things you didn't want to make the one thing you DID want actually work. Because JavaScript people think "modular development" means, "Every IF statement and bracket should be its own reusable package." Bower isn't even 10% as bad as NPM, so my advice is to simply install the components you want and leave Bower to handle the rest. The dependencies are listed in each component's package.json file or in the bower.json file.
