### ISSUE TITLE
Browser Refresh Delay not working

### ISSUE THREAD

**Issue by me-benni** [bdkjones/CodeKit#311]
**Quick, short summary:**
CK3 won't save the refresh delay.

**Expected results:**
When setting the delay it is saved.

**Actual results:**
It is not saved.

**Exact steps to reproduce:**
Set a Refresh Delay and from time to time it resets.
It resets on every restart of CK.

Also it is not written into `config.codekit3`
When settings it manually in `config.codekit3` and then starting CK, the correct setting is loaded, but it is reset to 0 in the config file.

**Comment by bdkjones** [comment]
Ah, I see what's going on here. The value from Project Settings is always rounded to the nearest integer when saved in the config file. I'll address this.

**Comment by bdkjones** [comment]
So, for example, if you set the delay to `0.75`, that's currently saved as `0`. Until I implement a fix, stick to refresh delays that are integer values.

**Comment by bdkjones** [comment]
It would appear that, for some shoddy technical reasons, it's not possible to link NSDecimalNumber to the stepper value in the UI; it's always going to revert to an integer. As such, the fix for this in the next version is that browser refresh delays must now be integer values between 0 and 6 seconds.
