### ISSUE TITLE
Feature Request: Multiple build process for each project

### ISSUE THREAD

**Issue by Shiva127** [bdkjones/CodeKit#315]
It would be perfect to have the possibility to create multiple build process for each project.

For example, I would like to have the possibility to make three builds for a project:

- one main build for development (`dev` directory) with browser refresh when files changes, expanded and commented files (Pug, Sass, etc.);
- one build (on request) for tests (`test` directory) which includes the files/directories for my tests (also with expanded and commented files);
- and a last one (also on request) for production (`prod`directory) where I can chose other files to includes (for example minified Vue.js, who is different from expanded one that I use in development build - with no warnings) and with all the files compressed (minified) and automaticly upload to my production server.

It could be so cool!

**Comment by bdkjones** [comment]
Well, the basic idea to live by is: "Develop like you're going to deploy." If you test everything unminified and separately, then minify it and combine it all only when you deploy, you're setting yourself up for some bad times. 

It's not necessary to have unminified files since most languages support Source Maps and your browser's inspector will automatically show the original, unminified source instead of the compiled output.

**Comment by Shiva127** [comment]
You're right for the source map.  But I like to see my Pug files expanded before Angular or Vue.js modify the DOM and I don't want source maps in production (yes, I can use filters in my FTP client but how to share these filter for everyone in the team?).

For the tests, you're right for the use of same files as production. But I don't want tests files/directories when I push everything in production (same as source maps).

And how to save the step of the scripted FTP push on the production server in the process only when it's ready for deployment (the only method now is to manually modify the process)?

And finally, I definitely don't use the same file for Vue.js in development and production.

**Comment by luxlogica** [comment]
@Shiva127 to be fair, you can do what you want outside CodeKit, and that may be preferable. While I think being able to have multiple builds in CodeKit could be useful, the focus of CodeKit is to *process files locally*, while the focus of the use-cases you mentioned is *deployment* - and this is a function that will be better handled by other tools in our workflow.

For instance: if you use **git** to version-control your projects, you can use git hooks to trigger scripts as you commit to specific branches. These scripts could then use tools like [git-ftp](https://git-ftp.github.io) to upload only the changed files. These tools all use text-based config files, which you can commit to your different branches, and share with your team.

If all this sounds too complicated - and it is - there are several graphical tools and online services that can help make the entire process easier for you. If your team is Mac-based, then you don't have to struggle with git in the command-line. There are several great programs that allow you to do all your git operations with a graphical interface, in a sane, comprehensible and visual way - like the awesome [Tower](https://www.git-tower.com) app. They also have a great [free eBook](https://www.git-tower.com/learn/) and a [video course](https://www.git-tower.com/learn/) for git newbies.

There are several online services that allow you to host your git repositories, and auto-deploy to your server when you push your commits. These services allow you to easily setup different deployment scripts for different branches of your code - i.e., so that when you commit to 'develop' it might upload certain files to your 'staging' server, and when you commit to 'master' it might upload a different set of files to your 'production' server. Most of these services even allow you to upload files to CDN and cloud services. Some of the ones you may want to look at include [Beanstalk](http://beanstalkapp.com), [Springloops](http://www.springloops.io) or [CodeBase](https://www.codebasehq.com) - all easy to setup and use for newbies. These services all come at a cost, however, and although they are easy to use, they can become quite expensive (specially for small companies, like ours).

There are low-cost and even **free** alternatives, such as Github, but these often require a lot more knowledge and manual setup - although you may also get more features... We settled with [GitLab](https://gitlab.com), which allows us to have unlimited free private repositories, and offers excellent features, including fully customisable **continuous deployment** via the amazing **[git-ftp](https://git-ftp.github.io)**. This tool automatically keeps track of which commit revision your server is at, and ftps only the change since your last upload.

I hope this information helps.
