### ISSUE TITLE
Compass - add_import_path not working 

### ISSUE THREAD

**Issue by ronn0** [bdkjones/CodeKit#317]
When i do use the `add_import_path` in my `config.rb` it runs out in an error:

> Libsass: Error: File to import not found or unreadable: test.
>        Parent style sheet: /Users/apple/repos/jouwfeestwinkel-magento-webshop/skin/frontend/ballonnenwinkel/jouwfeestwinkel/scss/stylestest.scss
>         on line 5 of Users/apple/repos/jouwfeestwinkel-magento-webshop/skin/frontend/ballonnenwinkel/jouwfeestwinkel/scss/stylestest.scss
> >> @import "test";           
>  

When i do it by command line everything works fine:
`/Applications/CodeKit.app/Contents/Resources/engines/compass/compass/bin/compass compile`

> write css/stylestest.css

I guess there is something wrong with the way the compass is called

**Comment by bdkjones** [comment]
A) compass is deprecated and has been end-of-lifed by its developer; it's time to move to something modern.

B) compass isn't being called here, likely because your config.rb file is in the wrong spot, so CodeKit doesn't recognize the project as a Compass project. Libsass is not compatible with Compass (hence a large part of the reason Compass is dead). Put your config.rb file in the project root folder.
