### ISSUE TITLE
Crash when saving SCSS using libsass on `max` function.

### ISSUE THREAD

**Issue by EvilClosetMonkey** [bdkjones/CodeKit#327]
**Quick, short summary:**

CodeKit 3 crashes when SCSS file saved with libsass enabled and `max` function is called.

**Expected results:**

Compiled CSS file based on default settings in CodeKit's SASS processing configuration.

**Actual results:**

The aforementioned crashing.

**Exact steps to reproduce:**

1. Modify SCSS
2. Save
3. Read crash log
4. Weep
5. Reopen CodeKit

**More details:**

(Note that all variations listed below work in `gulp-sass`)

I tracked the issue down to the `max` function. The following crashes CodeKit:

```
// $grid-breakpoints is a map
max($grid-breakpoints...)
```

Turning `libsass` off produces the following error:

```
Sass: Error: (1920px, 1919px, 1279px, 959px, 599px) is not a number for `max'
        on line 26 of /Users/pappas/Repositories/fleet2/scss/mixins/_breakpoint.scss
        from line 25 of /Users/pappas/Repositories/fleet2/scss/fleet.scss
  Use --trace for backtrace.
```

Switching up the call to:

```
max(map_values($grid-breakpoints)...)
```

... fixes the problem when *not* using `libsass`, but CodeKit still crashes when `libsass` is enabled.

**Comment by bdkjones** [comment]
@mgreter and @xzyfer would be the guys to ask. CodeKit 3.0.6 is running Libsass 3.5.0 Beta 3. Despite the beta tag, this release is production-ready and the latest version of node-Sass is also using it, I believe. It's possible this is a regression in Libsass if an older version of gulp-Sass handles it correctly.

**Comment by bdkjones** [comment]
Ok. I believe this issue should be fixed, but I'd like to test the implementation. Please download this special build of CodeKit: https://codekitapp.com/binaries/codekit-xpc.zip

You can safely replace your existing version of the app with this one. Try compiling your problematic code with Libsass using this version and, instead of a crash, you should see an appropriate error message in the log. 

If that's not the case, please reopen. And if the build works correctly, please let me know that to so I can ship it.

**Comment by EvilClosetMonkey** [comment]
Apologies for the delay. CodeKit no longer crashes, and an error message asking to disable 'libsass' now appears.

**Comment by bdkjones** [comment]
Ok, so with the Ruby compiler you get the error message listed and with Libsass you now get the "disable Libsass" message? Can you narrrow down the Sass that causes this and send me a file that shows the issue so I can investigate?
