### ISSUE TITLE
Projects keep disappearing

### ISSUE THREAD

**Issue by bradryanbice** [bdkjones/CodeKit#339]
I have a few projects loaded into Codekit, but aftrer closing and opening the app, the projects disappear and I get "No projects, Captain"

**Comment by bdkjones** [comment]
Do you see a message when the app launches about a "safe start"?

**Comment by bradryanbice** [comment]
I do not, and right now I'm trying to recreate it by opening and closing the app, but I can't consistently recreate. I'll keep trying other things.

**Comment by bdkjones** [comment]
Additionally, when filing bugs it's REALLY useful if you include relevant information. Which version of macOS? Which version of the app? It saves us both a bunch of time going back and forth.

**Comment by bradryanbice** [comment]
Sorry about that:

macOS Sierra 10.12.3
Codekit 3.0.8

**Comment by bdkjones** [comment]
CodeKit saves data to disk on two occasions:

1. When projects finish refreshing
2. When the app is quit normally.

If you force-quit the app or if you shutdown your Mac without gracefully quitting apps, it's possible that the app won't get the chance to save to disk.

**Comment by bradryanbice** [comment]
Everything I try (quitting normally in the middle of a build, force quitting when building, etc.) doesn't give me the missing projects so i guess I'll have to keep looking. It happens only occasionally, and it's not too hard to add projects back in. It's just jarring and annoying.

I'll keep looking for factors which may cause this.

**Comment by bdkjones** [comment]
I haven’t had any other reports of the issue, so there must be something in your specific environment causing the problem.

**Comment by bradryanbice** [comment]
Quite likely. I'll let you/this issue know if I find it.

**Comment by bradryanbice** [comment]
I found out that this issue was caused by AppTrap, which erased Codekit related files each time an update was installed. Now after updating, I'll need to choose not to erase these files.

**Comment by bdkjones** [comment]
It boggles my mind that people run stuff like this on their Macs. From what I can tell, AppTrap is an entire app dedicated to running in the background, waiting for a *.app bundle to be put into the trash, then finding and deleting a *.plist file associated with that app.

You're wasting CPU cycles, memory and battery life for...nothing. Extraneous plist files don't hurt anything; they're like 150kb. They sit in ~/Library/Preferences and never do a damn thing once their associated app is gone.

Whenever I get bug reports that are really off-the-wall, I have a mental list of stupid apps I inquire about because it's usually the case that these off-the-wall bugs are a byproduct of poor software choices. My list has grown today.

I recommend not running apps like this. It will make your life easier.
