### ISSUE TITLE
Update Bourbon and Neat bundled versions

### ISSUE THREAD

**Issue by electricbrick** [bdkjones/CodeKit#340]
Can you update the bundled versions of Bourbon, Neat, and Bitters to their most recent versions? The disparity caused me a bit of a headache recently.

**Comment by bdkjones** [comment]
I do that with every update. Bourbon is currently on the 5.0 pre-release version, actually. Neat and Bitters were up-to-date when the 3.0.8 release went out last week.

**Comment by electricbrick** [comment]
Weird. I just installed Neat 1.8 directly from 3.0.8.

**Comment by bdkjones** [comment]
Ahhh, I see what's happened here. You actually installed Neat 2.0 but the installation didn't include the top-level `_neat.scss` file that imports everything. This is because the structure of Neat changed in 2.0 and that top-level file got relocated. I'll update the installation routine in CodeKit to include it.
