### ISSUE TITLE
[Feature Request] Support for Yarn package management system

### ISSUE THREAD

**Issue by nwpappas** [bdkjones/CodeKit#368]
With Bower going EOL, support for an active package management tool would be advantageous.

Putting a vote in for Yarn. It does a great job, and that Bower is recommending it doesn't hurt.

**Comment by bdkjones** [comment]
Yep. I'm aware of the issue. Working on a migration plan.

**Comment by RichDonnellan** [comment]
+1 vote for npm.

**Comment by zcanter** [comment]
Yeah, great software regardless, but could really benefit with the integration of new package management system.

**Comment by MikeHarrison** [comment]
+1 for Yarn support for the reasons above

**Comment by jonasdumas** [comment]
+1 For Yarn support...

**Comment by jonasdumas** [comment]
By the way, thank @bdkjones for your great app !

**Comment by MikeHarrison** [comment]
Haha yep what he said ^

**Comment by ToniWonKanobi** [comment]
Yeah Yarn would be great ;)

**Comment by bdkjones** [comment]
So this obviously took a very long time, but it's shipping in 3.9 and it's very comprehensive. Bower remains supported for backwards compatibility, but npm is now the default and it's a much, much enhanced experience.

I debated Yarn vs. npm, but I got burned by relying on a smaller entrant before (Bower) and I'm not really looking to do that again. Plus, I'm not a big fan of Facebook and the latest versions of npm aped Yarn's major advantages. 

I also re-architected the entire way CodeKit handles package systems (which is why this took so long to do). This means that it should be relatively easy to add new package repositories in the future. For example, GitHub Packages.
