### ISSUE TITLE
ESLint Stylistic Issues Settings not Copied Over from Default Project Settings

### ISSUE THREAD

**Issue by romulis** [bdkjones/CodeKit#380]
**Quick, short summary:**
Setup up default project settings and when I created a new project some settings were not brought over to the new project. Specifically the ESLint Stylistic Issues settings.

**Expected results:**
All default project settings should be copied to new project.

**Actual results:**
I didn't fully check every single setting but right off the bat I can see that none of the settings from ESLint section on Stylistic Issues were copied over. It looks like all the main ESLint settings were but not the Stylistic Issues Section

**Exact steps to reproduce:**
Fill out Codekit default project settings with attention to ESLint section on Stylistic Issues. Create new project and check if that section was copied over.

**Comment by bdkjones** [comment]
Well, this is 100% a bug and it's caused by my own stupidity. In the screenshot below, there's a variable named `ruleActive`. If your project settings file doesn't contain an entry for that rule, I fall back on the "New Project Defaults" value. Except, as the arrow indicates, I never assign the freaking value to `ruleActive`.

<img width="595" alt="screen shot 2017-08-16 at 16 22 17" src="https://user-images.githubusercontent.com/926566/29389512-6c925c30-829f-11e7-8a2d-fbf613d5612a.png">

**Comment by bdkjones** [comment]
Ask me how many `NSLog()` statements I added to try to trace what was going on before I caught this nonsense. Answer: enough to make it faster to just revert in Git rather than manually delete them all.

**Comment by bdkjones** [comment]
Fixed for 3.3. Hope to push that live tonight.
