### ISSUE TITLE
JS error reporting pointer positioning

### ISSUE THREAD

**Issue by brianburkett** [bdkjones/CodeKit#382]
**Quick, short summary:**
The pointer in the JS error reporting for UglifyJS Minification doesn't line up. I think this just has to do with using a non-monospaced font.

**Expected results:**
Pointer to line up:
https://cl.ly/0N0Q0O250u0w

**Actual results:**
Pointer is misaligned:
https://cl.ly/132f2Q2q0k2L

**Exact steps to reproduce:**
Create a JS syntax error with UglifyJS minification turned on.

**Comment by bdkjones** [comment]
Ha, yea, it's because we don't use a monospace font in the log. I've asked for JSON output from various tools CodeKit uses so that I can present output in a prettier format, but Uglify's current main developer is a bit...grumpy.

So far, only Libsass gives me control over the output data so I can reformat it.

**Comment by brianburkett** [comment]
Ah. What about swapping out for a nicer monospaced font? Perhaps Panic Sans? :)

**Comment by bdkjones** [comment]
Swap complete. Menlo 11pt it is.

**Comment by brianburkett** [comment]
I don't remember agreeing to Menlo.

**Comment by bdkjones** [comment]
You will get comic sans AND YOU WILL LIKE IT.
