### ISSUE TITLE
Version 3.2 not recognizing html files included by slim templates

### ISSUE THREAD

**Issue by sathomas** [bdkjones/CodeKit#384]
In a `template.slim` file include an `.html` partial, e.g.

```
doctype html
html
    body
        include _test.html
```

CodeKit should recognize the inclusion and list the html partial as a linked file. It should also automatically re-compile the slim template when the html partial is updated.

Neither happens.

**Comment by bdkjones** [comment]
As far as I know, you can't include HTML files directly in Slim because the Slim complier interprets anything that's not a `*.slim` file as a `*.txt` file. I believe the HTML syntax in your partial would throw errors because it's not Slim syntax?

https://github.com/slim-template/slim/blob/master/doc/include.md

**Comment by sathomas** [comment]
That sounds plausible. Except I have an existence proof that it works. Here's the full contents of `_test.html`

```html
<h2 id="testpage">Test Page</h2>

<p>This is a test page to check out the various rendering options.</p>

<h3 id="mathequations">Math (Equations)</h3>

<p>Looks like display equations need to be enclosed in <code>$$</code> blocks.</p>

<pre><code>$${e^ {i\pi }} - 1 = 0$$
</code></pre>

<p>Here it is rendered:</p>

<p>$$
{e^ {i\pi}} - 1 = 0
$$</p>

<p>Note that there must be whitespace after the exponentiation symbol <code>^</code>; otherwise, the markdown compiler interprets it before the math processor has a chance.</p>

<p>And here it is inline <span class="math">\({e^{i\pi}} - 1 = 0\)</span> in <code>$</code> delimiters.</p>

<h3 id="code">Code</h3>

<p>Here&#8217;s a block of MATLAB code.</p>

<pre><code class="matlab">FNdata = cell(length(rangeI),1);
for idxI = 1:length(rangeI)
    I = rangeI(idxI);
    [t, X] = ode15s(@(t,X) dX_dt(t,X,I), tSpan, X_0, odeOptions);
    FNdata{idxI}.t = t;
    FNdata{idxI}.v = X(:, 1);
    FNdata{idxI}.w = X(:, 2);
end
</code></pre>

<h3 id="scripts">Scripts</h3>

<p>Looks like <code>&lt;script&gt;</code> blocks are okay. (That&#8217;s good)</p>

<script>
window.test = true;
</script>
```

**Comment by sathomas** [comment]
I wouldn't consider this a high priority issue, though. I'm just going to switch from `.slim` to `.kit` and (I expect) everything will work fine.

**Comment by sathomas** [comment]
To be clear. The html code above with the slim template above works fine if I manually compile it. The only bug is that CK isn't recognizing the dependency, so manual compilation is required.

**Comment by bdkjones** [comment]
Looked into this further. CodeKit already supports imports of any filetype in Slim files. What it does NOT support, currently, is the leading-underscore partial convention. This is because that convention is not in ANY of the Slim documentation related to `include` that I can find, so I had no idea the language adopted it. 

If you remove your leading underscore, I think you'll find CodeKit 3.2 recognizes the `include` just fine. 

Since the underscore convention does appear to be a *thing* in Slim, I'll add support for it in the next release. This is a prime example of how not writing good docs leads to issues.

**Comment by bdkjones** [comment]
Nope. Scratch all of that. Turns out I'm just an idiot. There's an edge case here I didn't account for and I've fixed it. This will work in the next release.
