### ISSUE TITLE
Changing output path for a language also affects imported files

### ISSUE THREAD

**Issue by greystate** [bdkjones/CodeKit#391]
**Quick, short summary:**

I added an old website project to CodeKit and adjusted some output paths (they weren't in line with my defaults for new projects) and then I changed a variable in an imported Less file. CodeKit then told me it had compiled 2 files successfully.

**Expected results:**

I expected the `styles.css` file to have been compiled using the new variable in the imported `constants.less` file.

**Actual results:**

CodeKit compiled two files: The imported variables file and the `styles.css` file, so now the was both a `constants.css` and a `styles.css` file in the output folder.

**Steps to reproduce:**

Link to sample project: [blankproject.zip](http://greystate.dk/resources/codekit/blankproject.zip)

- Download and unzip the sample project
- Add the project to CodeKit and observe that:
	1. `styles.less` imports `constants.less` and `mixins.less`
	2. `styles.less` is set to output to `styles.css` (i.e. to the same folder as its source file)
	3. Neither `constants.less` nor `mixins.less` has an output path defined. 
- Now change the project's settings for the Less language to output to the `public` folder instead and click the **Apply Changes To Existing Files** button (and confirm the choice if you get the "Are You Sure?" dialog)
- Now, even though `constants.less` and `mixins.less` are still imported by `styles.less`, they have been set to compile, and they've had their output paths specified.

So now, if I modify `constants.less`, CodeKit will compile `styles.css` **and** `constants.css` which is not at all what I'd expect.

I seem to have to remove the project and re-add it to CodeKit to get the intended setup back.

- - -

I _do know_ that this is kind of what I'm agreeing to in the "Are You Sure?" dialog, but it's really not what I expect (for imported files), and it hasn't always behaved this way (or, if I'm imagining things, older versions of CodeKit *did* at least restore the expected settings of the imported files after refreshing the project).

**Configuration (just in case)**

- **CodeKit** 3.2
- **macOS** 10.12.6

**Comment by bdkjones** [comment]
Excellent bug report. 

I agree that 99.99% of the time, you would not want imported files that are currently set to `ignore` to change to `copy` or `compile` when you apply those actions from Project Settings.

The Output Action is not changed during a normal project refresh because that action is set to `ignore` ONLY when the import link between the two files is first created—when you add the project to the app. Once that link exists, the Output Action is not automatically changed again. Otherwise, if you manually set an imported file to `compile` or `copy` for some reason (and people do), that setting would be wiped out the next time you refreshed.

I've changed CodeKit so that applying the defaults from Project Settings will no longer warp imported files that are set to `ignore` to anything else. However, if an imported file is set to `copy` or `compile` AND the Output Action you're applying from Project Settings is `ignore`, that action will be applied even to the imported files. 

Will ship in 3.3
