### ISSUE TITLE
 Crash attempting to compile typescript files

### ISSUE THREAD

**Issue by kimaldis** [bdkjones/CodeKit#412]
Repost after posting to wrong repro.

Seems to have started when I inadvertantly got into an import loop, file A import B, file B import A. I've fixed the loop but Codekit still crashes when I hit the Compile button or save a ts file.
I've tried removing the project, deleting the Codekit config file and re-adding the project but it still crashes. 

I've commented out all the import lines, it still does it on some files but not others.

Codekit 3.4, project can be found at https://www.dropbox.com/s/fn2bb9m9ypq4k4j/Daisy.zip?dl=0
Try compiling Cart/Add.ts by way of repro.

thanks.

**Comment by bdkjones** [comment]
Ok, I see what's happening here. 

There IS a small bug in CodeKit 3.4: the thing that scans for `import` statements in TS files is ignoring `//` style comments, so it finds line 12 in `summary.ts` where you import `edit.ts`, and `edit.ts` where you import `summary.ts`. That's the infinite loop and therefore the crash. 

I'll update this for 3.4.1 so that single-line comments are handled correctly. In the meantime, the workaround is to use block comments: `/* ... */`

**Comment by bdkjones** [comment]
This is more interesting. So you DO have a fairly complex dependency graph between these files:

![img_0012](https://user-images.githubusercontent.com/926566/32647972-a60f88ce-c5a8-11e7-9b69-c654900e588f.jpg)

Once I un-commented all of your commented-out `import` statements, I did find an infinite import loop: `edit.ts` imports `summary.ts` imports `edit.ts`. (This is not depicted in the photo above.) Because the comments were not being respected, this is what caused the app to hang and, eventually, as it ran out of memory, crash. 

Once I fixed the `//` comment issue, the hang/crash no longer happened, but your `add.ts` didn't compile correctly because TypeScript complained it couldn't find some symbols. To fix that, I had to un-comment the line in `edit.ts` where you import `summary.ts` (and create an infinite loop).

Except that, thanks to "modules"...this is no longer an infinite loop in the classical sense.

See, CodeKit still had logic in the TS compiler that dates back to before TypeScript had `import` and `referencepath`. In those days, you didn't have modules; you just had independent Typescript files that you wanted to concatenate into a single JS file. So CodeKit let you do that, but to figure out which files to put into that chain where, the app had to walk the `import` relationships between files.

Nowadays, you can import a module all over the place, without a care as to whether that creates import loops. As long as the compiler has access to the symbols `export`-ed by a module, it's fine. So, I've updated the logic in CodeKit 3.4.1 to handle this case. 

I'm not qualified enough in TypeScript to tell you if this structure is a good one, just that it's complex from a "let's figure out what depends on what" standpoint.

**Comment by bdkjones** [comment]
With all of that done, when I compile `add.ts`, I get this:

<img width="513" alt="screen shot 2017-11-10 at 00 11 10" src="https://user-images.githubusercontent.com/926566/32648659-b97353ac-c5ab-11e7-9f7a-729017872e29.png">

**Comment by bdkjones** [comment]
3.4.1 is live. Fixed.
