### ISSUE TITLE
Prevent cache-buster from encoding my {brackets}?

### ISSUE THREAD

**Issue by mrpatricko** [bdkjones/CodeKit#415]
Hi!

I'm using the new Cache-buster feature and am hoping there's an easy solution to my problem.

When using {bracket} variables in my CSS file path, the brackets are getting encoded during processing. 

before: "/source/scss/{variable}.scss"
after: "/build/css/%7Bvariable%7D.css?ckcachebust=532416645"

Is there any way to prevent this?

Thanks!

**Comment by bdkjones** [comment]
Yes: don’t use braces in file names. Encoding special characters in a URI like this is the standards-compliant way to handle them. There’s an RFC that describes it, but I can’t recall the number off the top of my head.

What is the reason you’re using braces here?

**Comment by mrpatricko** [comment]
I'm using ExpressionEngine CMS on a large site with multiple brands and styles. Having an EE {variable} in the CSS file path has been a saving grace as it prevents the templates from being overly verbose with if or case statements.

I figured I wasn't using Codekit Cach-buster as it was intended but wanted to ask anyways. You just never know. :)

**Comment by bdkjones** [comment]
Okay, but is that variable not resolved before the file gets to the cache-buster? In other words, something should be processing the file and swapping out that variable for some specific filename, right? You're not deploying it to the server in that condition?

**Comment by mrpatricko** [comment]
They're not resolved before sending to Cache-buster. The CMS processes the variables on the server.

**Comment by bdkjones** [comment]
Ah. I see. Well...that's a little complex because the URL-encoding function CodeKit uses to write these URLs is part of Apple's standard library. I pass it a string, it returns a properly-encoded (according to the official RFC) URI.

These braces are definitely a violation of the spec and they SHOULD be properly encoded in a URI. But the hard part is there's no way for me to "skip" them because I'm not writing the URI myself. 

The only real workaround I see is to flip off the cache-buster on files that contain these braces in URIs. Otherwise, you could add a Build Step to the very end of your Build process that opens the files, scans for the percent-encoding strings and replaces them with the `{` or `}` characters. This would ensure they are returned before you upload to your server, but it won't work as you save the files one at a time while working on them.

**Comment by mrpatricko** [comment]
Yea, my weird URI's are edge-case, for sure.

An option to pass characters to the allowedCharacters parameter would be outstanding. Maybe chalk this up as a 'Feature Request'. ;)

Now that I have a better understanding of Codekit's cache-buster, I'll look into some other work-arounds.

But I sure do appreciate your time and help, Bryan. Thank you!
