### ISSUE TITLE
Kit variables are blank when put next to a symbol

### ISSUE THREAD

**Issue by briantkatch** [bdkjones/CodeKit#425]
**Quick, short summary:**
When you have a symbol before a Kit variable (like @), the kit variable is removed but not substituted for it's value. The comment isn't in the HTML output, it just disappears.

E.g. this Kit

    
    support@

compiles to this HTML

    support@

where one would expect the output to be

    support@example.com

**Your configuration (any details about your system that you think might be relevant)**

I have a file `_config.kit` in my project with a number of Kit variables, including the above example of a domain name variable that I want to use to output a non-hardcoded email address on my page.

This `_config.kit` file is imported by `_header.kit`, which contains the code for my navigation bar and similar. `_header` is then imported by every page on my website, including the page I want to use this variable on.

I have tried directly importing `_config` on the page I want to use this variable on, but that does not fix the issue.

**Comment by bdkjones** [comment]
Using CodeKit 3.4.2?

**Comment by briantkatch** [comment]
Just downloaded 3.4.2 off the website and issue still exists.

(Sparkle never popped up and a manual update check didn't work - I wast still on 3.3)

**Comment by makshh** [comment]
@briantkatch for now you can use `support&#64;<!-- $domain -->`

**Comment by briantkatch** [comment]
@makshh Thanks, I'm using that as a workaround for now.

**Comment by bdkjones** [comment]
Good catch. I've found the issue and have fixed it for the next release.

Also, just FYI: the official syntax for variables is `<!-- $var = value -->` and not `<!-- $var: value -->`. The latter approach appears to work because CodeKit stops accepting characters as part of the variable name when it gets to the first one that's not alphabetic or numeric. Then, it discards all non-alphanumeric characters and whitespace until it arrives at the NEXT alphanumeric character, which begins the variable's value.

**Comment by briantkatch** [comment]
@bdkjones Thanks for the fix, I appreciate it.

Can you clarify about the syntax: Your [website's Kit documentation](https://codekitapp.com/help/kit/) says this:

> **Flexible Syntax**
> 
> You can use either $ or @ to denote a variable name. You can use equals signs, colons or just a space to assign a value.

I really prefer the colon syntax, but if it is in fact not the official syntax then I will change my codebase.

**Comment by bdkjones** [comment]
Goddammit. I had a feeling colons were allowed because I seem to recall a lot of time and effort spent adding the flexibility to handle them. I even went to the docs page to check before I wrote the statement above, but clearly I didn't look closely enough.

Colons are officially supported. I am a moron.

**Comment by bdkjones** [comment]
Also: what happened when you did the manual update check? Are you running CodeKit from somewhere on your Mac other than /Applications? Did you *first* run the app from a different location and then move it into place?

**Comment by briantkatch** [comment]
No problem.

As far as the Sparkle updater, it never popped up telling me that there was a new version, and when I manually checked for updates, I got this error, just with your logo: https://support.invisionapp.com/hc/en-us/article_attachments/115000432506/Screen_Shot_2017-01-05_at_3.02.07_PM.png

A quick Google says that it may be related to changes in macOS Sierra - I upgraded macOS from El Capitan to High Sierra without ever using Sierra, so I downloaded CodeKit while still on El Cap so this sounds plausible. 

CodeKit is running from /Applications, there is a reasonable chance that it could have been in ~/Downloads at first and then moved over to /Applications. Update checker seems to be working now though, it tells me that I am up-to-date.
