### ISSUE TITLE
.kit variable nesting / referencing

### ISSUE THREAD

**Issue by sebastianrilton** [bdkjones/CodeKit#431]
Thanks for an awesome app. I have a feature question:

Within the .kit language, would it be possible to allow a variable to be referenced from another variable?
Like this:

```
<!-- $var_a : ASDF -->
<!-- $var_b : $var_a -->
```

I know that you don’t want the .kit language to be too extensive, but this little addition would be so very helpful in my workflow.

**Comment by sebastianrilton** [comment]
Sorry to chase you on this @bdkjones , but would it in any way fit into the Kit language, or should I look into other languages?

**Comment by bdkjones** [comment]
It's *possible*, but it muddies the waters a bit. In Kit, all variables are simple strings, with the sole exception of setting a variable equal to `nil` to indicate "this is an empty string". If I do the above, then there has to be some sort of escape sequence involved for when you want to write a variable like this: 

    
    

This would now need to be something like:

    
    

Because there's no way for the compiler to know, definitively, whether `@somebody` is intended to be a string or a (missing) variable.

I'm not ruling it out, but it's definitely more complex than it appears.

**Comment by sebastianrilton** [comment]
Ok, thanks anyway!
