### ISSUE TITLE
Preview Server serves files outside of build folder

### ISSUE THREAD

**Issue by greystate** [bdkjones/CodeKit#432]
**Summary:**

CodeKit's webserver happily serves a file in the `<PROJECT_ROOT>/assets/` folder as if it existed in the `<BUILD_FOLDER>/assets/` folder.

I have attached a [reduced test case](https://github.com/bdkjones/CodeKit/files/1687510/isolated.project.zip) - this is a longer description of what happens:

The project looks like this:

<img width="279" alt="folder-contents" src="https://user-images.githubusercontent.com/5463/35707152-ffefc4a2-07a8-11e8-8dff-aae35e5f42c7.png">

- I've set CodeKit to ignore the top level `/assets/` folder
- The `/src/assets/` folder only contains one image
- When built, the `/build/assets/` folder only contains one image
- The HTML file references both images with a `src="/assets..."` URL

Both images are rendered, but the second one shouldn't, since the webserver has its root `/` URL in the `/build/` folder - right?

/Chriztian

[isolated project.zip](https://github.com/bdkjones/CodeKit/files/1687510/isolated.project.zip)

**Comment by bdkjones** [comment]
The reason this happens is because source maps are a giant goddamn pain in the ass.

Your build folder is technically the webroot of the project (or at least it should be; please confirm that’s the case in Project Settings > Browser Refreshing). But when CodeKit can’t find a file relative to the build folder, before it returns a 404, it checks relative to the project root folder. This is necessary because source maps need to retrieve the original files, which are not in the build folder. The trouble is: there’s no way to know whether a request for “somefile.js” is from a script tag on a page (which should just 404) or from the browser trying to resolve a source map (which should go up to the project root and look from there).

**Comment by greystate** [comment]
Ah - that explains it; It just happened a couple of times where I'd moved an image out to sanity-check something, and couldn't really understand why it didn't disappear... so thought I'd report it - it's not a giant problem for me at all...

Yes, can confirm the build folder is set as the webroot.

Feel free to close or file as low priority :-)
