### ISSUE TITLE
Preview Feature not working on Safari Version 11.0.3 (12604.5.6.1.1)

### ISSUE THREAD

**Issue by kimonostereo** [bdkjones/CodeKit#439]
Hi there! I've been away from CodeKit for a bit but recently loaded it and updated the app. I noticed that Chrome and FireFox preview reload fine when I am making changes to an .scss file but Safari either doesn't refresh it's preview or if it does, it shows an incorrect preview. The only way to get Safari to show the correct preview is to hit save twice on the file I'm working on.

I've removed all Safari extensions and rebooted macOS and the issue remains. Just curious if it's just me?

**Comment by bdkjones** [comment]
There's a few typical suspects for this. The most common is using a CMS that writes files to disk, such as Twigg. The old file is served instead of the new one because the refresh sequence happens before the CMS has a chance to write new file to disk. 

The other common cause is having OpCache enabled on your external server. This causes PHP to just reuse whatever it rendered last time rather than re-evaluating a PHP file. CodeKit can automatically disable OpCache in MAMP. It's in the Tasks menu.
