### ISSUE TITLE
license management: generate one key per user / license

### ISSUE THREAD

**Issue by DanielRuf** [bdkjones/CodeKit#440]
There is no overview how many of them are actually used, no possiblity to reject / unregister used licenses, make licenses invalid, ...

The UX could be better.

What if I would like to order more for a team where people come and go and keep control of the licenses?

**Comment by bdkjones** [comment]
You can additional seats to any license at codekitapp.com/purchase/ Just enter the same email address that the license is currently registered to.

If you want to do a single license per individual, the way to do that is a separate order for each person. The multi-seat license came about because for years organizations asked me for a way to use a single key for multiple Macs.

**Comment by DanielRuf** [comment]
This is not an ideal solution as the license key is the same when directly ordering multiple licenses .

**Comment by DanielRuf** [comment]
It would be better to have the ability to generate sub licenses if needed and revoke them if needed.

**Comment by DanielRuf** [comment]
Generating an email address for every possible future user? Not practical ;-)

You can take a look at Jetbrains and how they do it. For example I manage 2 keys there.

**Comment by DanielRuf** [comment]
https://github.com/snipe/snipe-it could be used for example.

**Comment by bdkjones** [comment]
I'll take a look at this for the next major release, but I can't do anything about it until then. Thanks!
