### ISSUE TITLE
[Feature proposal] Save paths separately from rest of codekit.config

### ISSUE THREAD

**Issue by ursbraem** [bdkjones/CodeKit#448]
**Quick, short summary:**

It would be cool to have more control over what is committed to versioning. So I had the idea codekit could save "team-relevant" information (paths, ignore...) to a file like `codekit.json` and all the other data (linting prefs etc) to `codekit.config`.

Maybe then, the "versionable" file would even become manually editable?

Impulses to post this were the following:

* codekit.config changes often, much more than your average gulpfile, probably at every update?

* I used to exclude config from git, saw on an older blog post of yours that you recommend versioning it though

* Bitbucket complains about it's size 😀

![grafik](https://user-images.githubusercontent.com/1446443/37649529-619435dc-2c32-11e8-9fe4-5f6ee0335303.png)

**Comment by bdkjones** [comment]
Well, the config file was never designed to be manually edited. I do have a couple ideas for reducing its size, but it’s still intended to be an opaque blob of data that just stores settings and transfers them between Macs.

**Comment by bdkjones** [comment]
So the issue here is a tradeoff between performance and the length of the config file. The vast majority of the config file is taken up by settings for each file in the project. My idea was to only record settings for a file when those settings differed from the "defaults" in Project Settings > Languages. But, the performance hit caused by asking whether a setting differs from defaults is not trivial at scale.

A project has 5,000 files. Each of those files has an average of about 6 options. For each file, we now have to check whether each of six options is different than the project defaults for the given language. That's 30,000 lookups—it starts to make a real impact.
