### ISSUE TITLE
Content Security Policy & Browser Refreshing

### ISSUE THREAD

**Issue by robin-garnham** [bdkjones/CodeKit#456]
This issue is to request a change to the way that CodeKit handled reverse proxying of traffic which is served with a CSP (Content Security Policy). 

My suggestion is that the policy is amended to add a nonce and then amend browser refreshing code to reference that nonce. 

Below is the error shown by Chrome when the website is served with a Content Security Policy which disallows inline scripts. 

Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-/dF/dVrimxYXIw8fBEm+oEj1vaAR9kBj6NgK797MrS0='), or a nonce ('nonce-...') is required to enable inline execution.

**Comment by bdkjones** [comment]
Okay, I've implemented support for CSP into CodeKit. The app should now correctly modify the CSP header so that browser refreshing just works.

Will you shoot me an email so I can get a test build over to you? I've done some basic testing here, but I want to make sure it works in the real world with varied CSP headers. bryan at codekitapp dot com.
