### ISSUE TITLE
CodeKit doesn't recognize linked SASS files with more than one _ to start the filename

### ISSUE THREAD

**Issue by joelschou** [bdkjones/CodeKit#458]
**Quick, short summary:**
I have a few SASS files that start with `__` or `___`, but CodeKit doesn't know to consider them linked to the importing files.

**Expected results:**
CodeKit would understand file links no matter how many `_` starts the filename.

**Actual results:**
It doesn't.

**Exact steps to reproduce:**
1. Create two files in the root: `main.scss` and `___setup.scss`.
2. In `main.scss` add `@import '__setup.scss';` on the first line. Save.
3. CodeKit compiles the first time properly.
4. Edit `___setup.scss` to add some garbage CSS guaranteed to throw an error. Save.
5. CodeKit doesn't recognize the file change.
6. In the CodeKit file browser, click on `main.scss` and then switch to the "Linked files" tab. Shows no _Imports_.
7. Click on `___setup.scss` in the file browser. Shows no _Imported bys_.

**A link to download a simplified project or file that shows the issue:**
https://www.dropbox.com/s/xt96sajm43tp2b8/CKbugtest.zip?dl=0

**Your configuration (any details about your system that you think might be relevant)**
macOS 10.13.4 on a 2016 15" rMBP
CodeKit 3.6.1

**Comment by bdkjones** [comment]
I can't decide which way I want to go on this. I understand *why* this is happening. You have written:

    @import '__file'

But that file's name is actually `___file`. CodeKit's import-linker first checks for '__file' and doesn't find it anywhere, so the linker follows a set of logical steps. The first is to swap the underscore. If the file HAS a leading underscore, it's removed. If it does NOT have one, an underscore is added. Then we check for THAT file. 

In your case, an underscore is removed and CodeKit looks for '_file'. That obviously doesn't exist. Because the import statement path already HAS an underscore, CodeKit doesn't consider *adding* another underscore because...well...in the history of the world, you're the only person who's ever tried using more than one.

So the fix is relatively easy. However, it does entail a minor performance penalty because now CodeKit has to, for every Sass import, consider adding and removing an underscore, no matter what's going on with the original filename. 

This naming convention seems pretty crazy to me. It's virtually impossible to tell how many underscores are in the name and it's super easy to type the wrong number in your editor. Where did you pick up this habit and why use it?

**Comment by joelschou** [comment]
You can go ahead and tooooootally disregard. This isn't so much a habit as something I was experimenting with for file organization for a pretty gnarly multi-layered templating process. I ended up shifting gears to a completely different approach, not because of this issue, but because I didn't like the rabbit hole down which this approach sent me.

I appreciate the time you took to look into the issue and write a nice response. That makes complete sense to me and it's such a bizarre edge case you shouldn't bother doing anything that would slow down CK's exceptional performance. Thanks again.
