### ISSUE TITLE
[Feature Request] Strip HTML comments during build

### ISSUE THREAD

**Issue by Bangkokian** [bdkjones/CodeKit#462]
Very simple feature request here: 

It would be great if the Build process had a native option to strip out `<!-- HTML comments -->` and omit any blocks of commented-out HTML during the build.

**Comment by tiptronic** [comment]
+1 - this is indeed needed.
For now I must manually remove the comments. 
Note: This is less a problem for removing white-space, but we have features in JS/HTML frequently, which we don't want to expose to the public.

**Comment by katerlouis** [comment]
+1

**Comment by bdkjones** [comment]
Implemented for 3.8.

I didn't stop at just comments; CodeKit now has a full-blown HTML minifier built-in. Like the cache-buster, it's available on any file type that can compile to HTML, including any custom file types you may add to the app.

I've spent a lot of time looking at edge cases and ultimately decided not to expose options for the minifier right now. Instead, I've hard-coded defaults that are safe. All comments get stripped, extra whitespace gets removed, etc. I may expose options in the future; we'll see how this goes.

The minifer is OFF by default, since it may still break your page. This is especially true if you try to run it on something that is not valid HTML or that's not HTML at all. It's an opt-in feature, but it's ready to go.

**Comment by Bangkokian** [comment]
Awesome!

**Comment by tiptronic** [comment]
👍

**Comment by JayHoltslander** [comment]
Awesome.
Will it still work if you’re saving html files as “.php”?

**Comment by bdkjones** [comment]
The short answer is....I don't know. Possibly?
