### ISSUE TITLE
AppleScript API to process a specific file

### ISSUE THREAD

**Issue by zengabor** [bdkjones/CodeKit#463]
Building the entire project is possible already but unnecessary and slow. I need to trigger a specific file:

    tell application "CodeKit" to process "~/myproject/myfile.kit"

This would make CodeKit even more awesome.

**Comment by bdkjones** [comment]
You got it. Added for the next release. The syntax is:

    tell application "CodeKit" to process file at path "/Users/bdkjones/Desktop/tsref/main.ts"

**Comment by zengabor** [comment]
Great news, thank you so much!

Just out of curiosity: will CodeKit always respect the setting of that specific file? So if the file was set to "copy" or "ignore" will CodeKit copy or ignore it instead of processing it?

**Comment by bdkjones** [comment]
If the file's Output Action is `copy` then CodeKit will copy the file to its output path. If the file's action is `Ignore`, however, the app will process the file as if it's Output Action were set to `Process`. This is because you're *explicitly* telling the app to do so, just as if you had selected the file in the UI and clicked the "process" button.
