### ISSUE TITLE
TextPattern variables and Cache-Busting

### ISSUE THREAD

**Issue by richtestani** [bdkjones/CodeKit#479]
I use TextPattern for a project, and noticed when I use a variable in my src, CodeKit will not cachebust this item. Likely due to TextPattern HTML like syntax:

`<script src='<txp:variable name="assets" />/path/myscript.js'></script>`

The above will fail. Not a terrible thing in the world, but if it's something worth noting, there it is.

**Comment by bdkjones** [comment]
Hmm, I’m not sure there’s much I can do about this. Stuff like variable paths should be resolved *at build* rather than on page load on the user’s machine. You could do this variable path bit with Kit, Jade, Haml, or Slim, have a hard-coded path in the output file and then have that cache-busted as appropriate.

**Comment by richtestani** [comment]
Correct, and TextPattern will render the final variable when the page is requested, but when CodeKit runs the cache-busting upon a script tag like the one above, it skips over it. I'll look into using a variable in one of your suggestions.

Thanks you for your response and your product!.
Rich
