### ISSUE TITLE
[Feature Request] implement a base64 encoding function

### ISSUE THREAD

**Issue by dergraph** [bdkjones/CodeKit#480]
as discussed on email with you.
a base64 encoding method of partials could be usefull.
wether within the kit files inserting contents as base64
or within css files wether its fonts or images people may wanna fill contents in that way.

**Comment by bdkjones** [comment]
Okay, I've knocked this out. You can now do this in a Kit file:

    <img src="data:image/png;base64, ">

Alternately, `@include-base64` works as well.

I spent a good bit of time looking for the most optimized base64 encoding algorithm I could find. The one I chose is, of course, pure C.

Shoot me an email so I can get you a build to try out. I've done some limited testing over here but I'd like to get real-world examples to make sure the implementation is robust.

**Comment by bdkjones** [comment]
As for making this functionality available in other languages (CSS, Sass, Pug, etc): that's out-of-bounds for CodeKit. Doing so would break compatibility of those languages with other, non-CodeKit tools, since they'd have no idea what `@import-base64` means. 

However, in most of those languages, you could pretty easily write your own base 64 encoding function and call it as needed.

**Comment by dergraph** [comment]
yea can u send a build over?
happy to try it out.

⌘

Thomas Helbig
(+49) 176 66 89 43 62

**Comment by bdkjones** [comment]
Please send me an email: bryan at codekitapp dot com.
