### ISSUE TITLE
Passing .kit variables to imported/included JS code.

### ISSUE THREAD

**Issue by macfire** [bdkjones/CodeKit#482]
**Summary:**
When using a .kit file, I would like .kit variables to be passed to  JS and CSS files that are include/imported.

**Example:**

_index.kit_
```html
<body>
...
<!--$kit_var = 'My Variable' -->
<script type='text/javascript'>
    <!-- @import "window_onload.js" -->
</script>

</body>
```

_window_onload.js_
```javascript

window.onload = function () {
    var my_var = <!--$kit_var-->;
    console.log('my_var', my_var)
}

```

**Expected results:**
_index.html_
```html

<body>
...
<script type='text/javascript'>
window.onload = function () {
      var my_var = 'My Variable';
     console.log('my_var', my_var)
}
</script>

</body>
```

**Actual results:**
_index.html_
```html

<body>
...
<script type='text/javascript'>
window.onload = function () {
      var my_var = <!--$kit_var-->;  // <-- variable not rendered :(
     console.log('my_var', my_var)
}
</script>

</body>
```

**My current solution:**

Append '.kit' extension to import JS file name.
E.g. _window_onload.js.kit_

_index.kit_
```html
<body>
...
<!--$kit_var = 'My Variable' -->
<script type='text/javascript'>
    <!-- @import "window_onload.js.kit" -->
</script>

</body>
```

**Works correctly (as expected).**
_However_, it would be nice (convenient) to not have to add '.kit' extension to JS files.

_P.S. In Pycharm, I was able to map '*.js.kit' to Javascript language, so I have a work-around to keep code checker working._

**Comment by bdkjones** [comment]
The current “workaround” approach is the correct one. A file that wants to use Kit features needs the *.kit extension—that’s what tells CodeKit to look for and process Kit statements in that file. 

If Kit statements were allowed in ANY file, CodeKit would have to scan every single file for them (slow) and other developers would have no idea that this JS file isn’t *REALLY* a JS file, because it won’t work without the Kit compiler processing it first. By appending *.js.kit, you solve both problems.

Similarly, you can’t write PHP in a *.html file, nor Sass in a *.coffee file. The extension needs to indicate what the content of the file is.

**Comment by macfire** [comment]
Your reason makes sense.
Thanks for reply.

--
via phone
