### ISSUE TITLE
[Feature Request] Replace Uglify with Terser (or provide as an option)

### ISSUE THREAD

**Issue by dwkns** [bdkjones/CodeKit#497]
### **Feature request**
Replace Uglify with [Terser](https://github.com/terser-js/terser)

**Why**
Uglify-es is [no longer maintained](https://github.com/mishoo/UglifyJS2/issues/3010#issuecomment-374018994). Uglifuy-js doesn't support  ES6+ (its ES2015 only).

ES6+ is increasingly being supported in browsers and certainly increasingly used during website/web app development. It should have a first class mangler/compressor rather than having to rely on babel to work.

Terser retains API and CLI compatibility with uglify-es and uglify-js@3.

It should also allow minification before bundling which [may lead to build time improvements](https://medium.com/@adamhooper/make-uglifyjs-way-faster-by-using-it-sooner-c2c39a9ad27e).

**Comment by bdkjones** [comment]
Yea, I’ve been keeping an eye on the es branch of Uglify. The issue is that there are still too many bugs for production use. Once it matures enough, I plan to include it

**Comment by seanCodes** [comment]
[According](https://github.com/mishoo/UglifyJS2/issues/3156#issuecomment-392943058) to the current Uglify maintainer:
> `uglify-es` is no longer maintained.

And in fact, it looks like the `uglify-es` branch of Uglify JS has actually been deleted.

I think [Terser](https://github.com/terser-js/terser) has emerged as the clear successor and has proved itself as more than just a fork at this point. It’s also very actively maintained. Since it has the same API/CLI as Uglify, it should be a fairly invisible transition for both the app and users. 🤞

Supporting mangling/compression of ES6 code is a key part of bringing CodeKit up-to-date with the ES6 world, so it would be great to see it implemented.

**Comment by bdkjones** [comment]
Yea, I’m just very wary of incorporating unproven tooling. Uglify-es was buggy and ES6 itself is much more complicated to properly minify. And nobody is shipping ES6 code to Browsers without transpiling yet—we’re a few years away from that, at least.

**Comment by dwkns** [comment]
Terser is now the default minification for Webpack. 
https://github.com/webpack/webpack/pull/8392

**Comment by bdkjones** [comment]
Done. 

CodeKit 3.8 has Terser built-in. It replaces UglifyJS. All applicable options that carry over from Uglify are automatically migrated for every project. New options are shown in the UI. Additionally, I'm forcing the `comments` option to `OFF` in 3.8 because the meaning of that option got inverted in Uglify 3 and everyone has no idea why comments are showing up in minified files now and I'm tired of writing the same email reply.

**Comment by bdkjones** [comment]
Should be out in a few days, once I get the docs done. If you'd like you can try it now at https://codekitapp.com/binaries/beta/bundle7.zip
