### ISSUE TITLE
With Wordpress themes, when mamp hostname and theme folder name are the same Codekit fails

### ISSUE THREAD

**Issue by onuro** [bdkjones/CodeKit#513]
Ok so the here's how it is:

I have a MAM webhost of "bavarian" with a wordpress installation in it with the theme active I'm working on, again named "bavarian".

I choose "http://bavarian" for external server in Codekit and preview, the styles fail to load since it replaces my theme name in the stylesheet url as well.

"http://onurmbp-3.local:5757/wp-content/themes/http://onurmbp-3.local:5757/assets/css/vendor/bootstrap.min.css"

Where the second  http://onurmbp-3.local:5757 should be "bavarian".

You get what I mean? :)

**Comment by bdkjones** [comment]
http://bavarian is not a valid address. That's why you're having this problem. For speed, CodeKit simply swaps every occurrence of the external server name with the proxy server. So if you name your external server `the`, then every instance of `the` gets replaced on the page.

You need a valid address with a TLD such as bavarian.site, bavarian.project, bavarian.anything. Do not use .dev.
