### ISSUE TITLE
make commons fonts for multiples projects and export it on the build for one project

### ISSUE THREAD

**Issue by benfci** [bdkjones/CodeKit#516]
Hello, i can't find a solution about what i'm trying to do.

My problem is, i've got multiples projects which all have commons fonts and every time i make a new project i'm duplicating those fonts (thats what i'm trying to avoid).

So i'm making commons devs files on my framework which is working for my sass files but not for my font files.

When i'm building the project, the fonts are not exported and in my css file the font-face isn' working cause it won't find the proper path.

i already tried to make a compiled font.css and imported it but ofc since it's compiled to css i've all the font loaded but thats not what i want, i want to load only the font i need for the project i'm using on so not all fonts.

Do you have any idea or is it just impossible to do so with codekit ?

**Comment by bdkjones** [comment]
The trouble is that the font file needs to be on your server when you deploy each project. That's why it's not eligible to be part of a CodeKit Framework. Files in Frameworks are meant to be imported into other files so that a copy of the original file is not needed; it becomes part of the file into which it's imported.

Each of your projects needs a copy of that font file to be a self-contained website.
