### ISSUE TITLE
Root-relative prepend/append for javascript

### ISSUE THREAD

**Issue by otheroom** [bdkjones/CodeKit#518]
I've refactoring a large project that I've got in CodeKit and was happy to find that instead of doing something like this:

```
<!-- @include ../../../library/kit/_template.kit -->
```

I could do this:

```
<!-- @include /library/kit/_template.kit -->
```

It would be very nice if the javascript @codekit-prepend and @codekit-append directives could also allow root-relative path specifications.

**Comment by bdkjones** [comment]
Oh sure, why not? 

The `@codekit-prepend/append` statements are about to be deprecated in the next release in favor of using ES6 modules. However, CodeKit will never drop support for them so that older projects continue to work. They just won't receive any new enhancements...other than this one because I'm in a close-issues mood tonight. 

Implemented for 3.8.
