### ISSUE TITLE
Use filename revving instead of query-string parameters for Cache-Busting

### ISSUE THREAD

**Issue by dgotilla** [bdkjones/CodeKit#521]
Hi Bryan,

Have you considered filename revving instead of query-string for cache-busting?

This:
`<script src="file-0b5a866de46caca8e9.js" />
`
Instead of:
`<script src="file.js?ckcachebust=0b5a866de46caca8e9" />
`

Webhint (the web linting tool) recommends against (https://webhint.io/docs/user-guide/hints/hint-http-cache/) query-string parameter revving because popular proxy software may not cache files with query strings (https://www.stevesouders.com/blog/2008/08/23/revving-filenames-dont-use-querystring/).

Thanks for your time and keep up the great work!

Regards,
Daniel Gotilla

**Comment by bdkjones** [comment]
Yes, I have considered and rejected that approach because it almost guarantees that something on the website will break. Especially with CMSes and WordPress and such. By contrast, the query strings will never break a website—the worst outcome is just that the cache isn't busted.

The correct approach is to use *good* proxy software that properly accounts for all possible variations of URIs. Cloudflare is my recommendation.

**Comment by dgotilla** [comment]
I do use CloudFlare for my projects but I can't control the proxy software on the end-user's side (i.e.: corporate networks).

I understand the possible impacts on CMSs but perhaps an opt-in feature/toggle for static websites?
