### ISSUE TITLE
CodeKit keeps refreshing

### ISSUE THREAD

**Issue by dwd0tcom** [bdkjones/CodeKit#531]
**Quick, short summary:**
CodeKit keeps refreshing my project all the time and it's impossible to work with it.

**Expected results:**
Refresh just when there is a change in the project files

**Your configuration (any details about your system that you think might be relevant)**
I use the latest CodeKit release for my projects, together with MAMP 5.0.1 and both are running under the latest macOS.

**Comment by bdkjones** [comment]
If by "refresh" you mean CodeKit keeps re-indexing the list of files in your project, that's usually caused by:

1. Dropbox or other syncing software. Pause it if your project folder is in a syncing folder.

2. CMSes that write log files to disk when they load a page. This creates an infinite feedback loop because CodeKit is designed to respond to file-change events.

I'll need more details and exact steps to recreate the issue if the problem persists after you check the above.

**Comment by j3kz** [comment]
I have the same issue, just after saving or updating one file.

Looking at my project with `fswatch -rtx project_dir`, I get:
project_dir/myfile.coffee Renamed PlatformSpecific AttributeModified IsFile
project_dir/myfile.js Created Updated IsFile
project_dir/myfile.js.map Created Updated IsFile
project_dir/config.codekit3 PlatformSpecific Updated IsFile
project_dir/config.codekit3 PlatformSpecific Updated IsFile

The two last config.codekit3 are always updated (for each file I save) and can take forever... if I try to save/update before end of refresh, the new content is not processed !

**Comment by bdkjones** [comment]
1. Which other apps are running on your Mac? 
2. Is the project folder on your local disk, an external drive, or a network-connected volume?
3. Are you previewing the project in your web browser while saving the file?
4. Which CMS or platform does the project use?

**Comment by j3kz** [comment]
1. text editor (Panic Coda) + Safari + Chrome (Apple Mail in background)
2. local disk
3. no previewing, with/without nodemon gives same results
4. no CMS, only node server
I tried to make my configuration as simple as I can to solve this problem and before issuing.

Additional information: config.codekit3 size is about 800kb.

Why config.codekit3 is updated twice ?

**Comment by bdkjones** [comment]
Shut down the node server and see what happens.

-Bryan

**Comment by j3kz** [comment]
When nodemon is not running node server is shut down...

**Comment by bdkjones** [comment]
You have something running that’s changing files in the project folder OTHER than your editor. CodeKit is seeing that file-change event and re-indexing the project in response. The usual culprits are syncing services, backup services, CMS systems that create log files on disk, etc.

To verify that, zip the entire project and send me a download link so I can test it over here.

**Comment by j3kz** [comment]
fswatch does not report other file changes in the project directory than the file I save (see my post).
Codekit detect the file change, but the refreshing process takes a lot of time. Unfortunately, during this process all other file changes are ignored and will not be processed. As a result, the project is unsynchronized.

I'm sorry, I cannot send you the sources of the project. Basically it is a node server written in coffeescript. If you have a Codekit development version with performance monitoring I would be glad to help...

2 questions:
- why refreshing the whole projet each time a file change ?
- would refreshing be in a separate thread ?

**Comment by bdkjones** [comment]
The results from fswatch aren't reliable.

Do you have any security software running on your Mac?

When you add or remove a file from the project, CodeKit re-indexes the entire project because that new or deleted file can affect any other files in the project. For example, another file might import it. The only way to establish those relationships is to re-index the project. This does not happen when you save a file from your editor—in that case, the file-change event signature is different and CodeKit compiles the file.

Without the project to test, there's little I can do to help. You're welcome to boil the full project down to a smaller subset of files that still show the issue.

**Comment by j3kz** [comment]
Another test:
1. `mkdir Documents/CodeKit`
2. Setup a new CodeKit project to watch this folder and enable only this project.
3. `echo '#' > Documents/CodeKit/file.coffee`
4. triggers CodeKit state: Refreshing "CodeKit", the process take about 30s...

**Comment by bdkjones** [comment]
That sequence of events is 100% correct behavior. You’re creating a new file in the folder. CodeKit is rescanning the project folder in response (again, because there might be OTHER items in the folder that import or depend on the item you just added and the links between files must be established so that when you save a file that is imported into another, the PARENT file gets compiled.)

**Comment by bdkjones** [comment]
The fact that it’s taking 30 seconds is not normal. That implies that your data file has been corrupted. Quit the app and relaunch it while holding down the Option key. Choose “Safe Start” and you’ll get a fresh copy of the app. Re-add the project or repeat your test steps.

**Comment by j3kz** [comment]
"Safe Start" solved the problem ! Thanks

**Comment by anton100** [comment]
I had the same problem, found out that iCloud was the culprit. The desktop keeps on refreshing because of iCloud. Work now with CodeKit in the website folders I'm editing.
