### ISSUE TITLE
Can not get a simple compression with import

### ISSUE THREAD

**Issue by rvola** [bdkjones/CodeKit#538]
**Quick, short summary:**

The codekit-prepend command is deprecated.
In some project I use codekit to create a file without including bower_components in my project

**Expected results:**

Get usable compression.

**Actual results:**

In the test folder you will find a stock config.
An addiction is called 'jQuery'
I do not want to leave the bower_components folder on the server. I will create a file that will compress or copy the file I need.

You will find in the export folder 1 file using the technique "import" and another "codekit-prepend".

Finally the index-xxx.php files call the different versions.
In the case with the method "import" jQuery does not work (console error)

Codekit-prepend is useful for copying dependency files and sometimes for compressing them when they are not.

**Your configuration (any details about your system that you think might be relevant)**

Mac High Sierra 10.13.6
Codekit 3.8.2

**Comment by rvola** [comment]
[test.zip](https://github.com/bdkjones/CodeKit/files/2965287/test.zip)

**Comment by bdkjones** [comment]
Please watch the screencast about bundling at https://codekitapp.com/videos/

The reason your bundle is failing is that you're importing jQuery without assigning it to the `$` symbol, which is why it's undefined in the browser.

**Comment by rvola** [comment]
Yes, I watched the video well.
Even adding this, it still does not work.
`import $ from "./../bower_components/jQuery/dist/jquery.js"`

**Comment by rvola** [comment]
otherwise my only goal is to have a file that compresses another file.
codekit-prepend did the job very well

**Comment by bdkjones** [comment]
First: The legacy `@codekit-prepend/append` statements are still available.

Second: The reason this example is failing is because you're importing jQuery into a file, including that file in your HTML document, then using a separate `<script>` tag on the page to attempt to access the `$` symbol, which is not available in a global scope. It's available to the file where you imported jQuery.

Move the code that uses jQuery from the separate `<script>` block in your HTML document to the file where you've imported jQuery. It will then work.

There is zero reason to import jQuery into a file simply to minify it. If you want to use the minified version of jQuery on your HTML page, you're much better off just using the pre-minified version of jQuery that's available in that bower_components folder.

**Comment by bdkjones** [comment]
In short: ES6 Modules are scoped. Importing something into a file does not make that imported thing available globally to scripts in other files (or in other `<script>` tags, in this example).

**Comment by rvola** [comment]
ok I understand better.
I use this compression model for two concrete examples.

The first in a WordPress theme, I often replace the jQuery provided by WP by that of the theme.
Unfortunately a lot of plugin and WordPress will call Javascript outside the files. So import can not replace codekit-preprend in this case.

Then it happens very often to have uncompressed dependencies. I regularly use codekit-prepend to get a compressed version regardless of the bower that can be updated without copying again / move the file of the bower in my environment.

I think you have to keep codekit-prepend that does a useful job in some cases.

Thank you for the help
