### ISSUE TITLE
Installing npm packages failing

### ISSUE THREAD

**Issue by modermo** [bdkjones/CodeKit#549]
**Quick, short summary:**
Attempting to install npm packages is causing CodeKit grief. I'm not sure if it has something to do with my instance/project, or is a known-issue

**Expected results:**
I expect the npm packages to install

**Actual results:**
I am getting this error:

```
npm failed to install packages and the error message it produced was malformed JSON, so CodeKit can't display details. The raw output from npm was: 

/Applications/CodeKit.app/Contents/Resources/engines/node/lib/node_modules/npm/bin/npm-cli.js:84
      let notifier = require('update-notifier')({pkg})
      ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```

**Exact steps to reproduce:**
I tried to install `vue` from the package manager

**Your configuration (any details about your system that you think might be relevant)**
Happy to provide what is necessary here. Not sure whether to just copy/paste my entire `config` file.

**Comment by bdkjones** [comment]
Just tested over here and `vue` installed correctly:

<img width="1376" alt="Screen Shot 2019-07-24 at 21 56 07" src="https://user-images.githubusercontent.com/926566/61847010-ffe68600-ae5d-11e9-8898-f8a653b072ce.png">

It's hard to say what the exact cause is because there are SO MANY GODDAMN THINGS that break JavaScript. A few things to try off the top:

1) Do you have any global packages installed or any global npm configuration that might be running a post-install script?

2) Clear out all the garbage npm dumps in your home folder: `.cache`, `.npm`, `.local`, `.config`. Those are all hidden files; you'll need to show hidden items in the Finder to see them or use `rm` in Terminal.

3) If you have node.js and npm installed on your Mac outside of CodeKit, make sure those are up to date.

**Comment by modermo** [comment]
1. I don't believe so. 

2. I ran `npm cache verify`, but I'm not sure if that properly cleared everything out.

3. Upgraded to the latest version of node `v12.7.0`. `npm version` yields this result:

```
{
  npm: '6.10.0',
  ares: '1.15.0',
  brotli: '1.0.7',
  cldr: '35.1',
  http_parser: '2.8.0',
  icu: '64.2',
  llhttp: '1.1.4',
  modules: '72',
  napi: '4',
  nghttp2: '1.39.1',
  node: '12.7.0',
  openssl: '1.1.1c',
  tz: '2019a',
  unicode: '12.1',
  uv: '1.30.1',
  v8: '7.5.288.22-node.16',
  zlib: '1.2.11'
}
```

Also tried running in a new project/folder to ascertain it isn't project specific. Still got the error.

**Comment by bdkjones** [comment]
Do you have a second Mac you can test it on? If not, try creating a new user account, logging out of your current account and into the other one (do not use fast-user-switching) and see what that yields.

**Comment by modermo** [comment]
I just created a new user account and properly logged in (and logged out) and it's giving me the same error.

Any additional logs/config you'd need me to provide? It's an awesome feature and I'm really looking forward to playing around with it :)

**Comment by bdkjones** [comment]
Try installing a different package, like jquery. Do you get the same issue?

It *sounds* like for some reason npm's CLI isn't running in strict mode on your machine.

**Comment by modermo** [comment]
Just tried a couple of different packages. Same issue unfrotunately. 

I do have NPM running on my machine for a host of other projects, but it's not a problem for any of them. 

This might be a dumb question, but is Codekit using its own instance of npm? 

Things I've tried:

1) Running `nvm ls` results in:

```
         v8.4.0
        v10.8.0
->      v12.7.0
         system
default -> node (-> v12.7.0)
node -> stable (-> v12.7.0) (default)
stable -> 12.7 (-> v12.7.0) (default)
iojs -> N/A (default)
lts/* -> lts/dubnium (-> N/A)
lts/argon -> v4.9.1 (-> N/A)
lts/boron -> v6.17.1 (-> N/A)
lts/carbon -> v8.16.0 (-> N/A)
lts/dubnium -> v10.16.0 (-> N/A)
```

So it's not like I'm using an old version of node (which is what the rest of the interwebs diagnoses the problem as). 

2) Seeing if I have npm installed in two locations as per this [stack overflow](https://stackoverflow.com/questions/50316693/npm-update-broke-npm). No dice.

**Comment by bdkjones** [comment]
Yes, CodeKit uses its own internal copy of npm. BUT that can change depending on your PATH environment variable. You also ha e the non-stable version of Node installed, which may make a difference. I haven’t received any other reports of this issue, so it’s definitely something isolated to your Mac and configuration.

**Comment by bdkjones** [comment]
Try completely removing Node from your system and then installing the LTS release (currently 10.17 I think)

**Comment by modermo** [comment]
Completely uninstalling node then reinstalling fixed the problem. Thank you kind sir!

**Comment by bdkjones** [comment]
Great; glad you got it sorted!

**Comment by schmidthaus** [comment]
Hi Bryan. I had the same issue and it turned out to be me not setting the Package.json folder path under the npm tools setting.

The default blank setting assumes the package.json to be located in the project root folder. I guess this is normal, but on this project, my project root folder was not the folder containing the package.json file for the project. An easy oversight. Updating the path solved the npm failed to install error.
