### ISSUE TITLE
CodeKit is "processing" ALL of my project's files. How do I make it stop?

### ISSUE THREAD

**Issue by coredumperror** [bdkjones/CodeKit#563]
I just use CodeKit to build my Sass. It's worked great for that for years, but some time in the recent past, it decided that it wants to process *every single file* in my project directories, including `.py` files, `.txt` files, `.cfg` files, etc. It can't actually _do_ anything to them, but it still pops up a Growl notification every single time I save a file.

This is super annoying, and I want it to stop, but nothing I've been able to find in the settings does "Ignore everything except .scss files, please". How do I do this? Or at least something similar.

I'm on MacOS Mojave (which _might_ be related? I upgraded to Mojave relatively recently, too), and I currently use CodeKit 3.9.2. I do all my development in PyCharm.

**Comment by bdkjones** [comment]
If your project is using a Build Folder (and it definitely should be in 2019), what you're seeing is CodeKit copying files from the source location to the build folder as you change them. That's entirely correct and if you stop it, your build folder won't contain the correct files until you manually build the project by clicking `Build Project` in CodeKit's UI. Your browser preview will likewise be outdated and incorrect until that's done.

If you are not using a build folder, you control the Output Action for file types in `Project Settings > Langauges`. Set as appropriate and then click the `Apply To Current Files` button to change all files of a given type to the new settings.

You can also configure this as the default for new projects in `File > Defaults For New Projects`. 

I do NOT recommend turning everything off and leaving only Sass enabled. Instead, flip on the Build Folder checkbox in `Project Settings > Build` and then let CodeKit process as normal. Otherwise, what's going to happen to you down the road is that you'll start wanting CodeKit to do something else (like optimize images, minify JS, etc.) and you'll think the app is broken because you set different defaults.

**Comment by coredumperror** [comment]
Please excuse my ignorance, but I'm honestly not sure what a Build Folder would even **be** for my type of project. I write Django webapps, so as far as I know, there's no reason for CodeKit to want to copy any of the files around inside my project folder. 

The only thing like that which really makes any sense to me is how CodeKit builds my `.scss` files into `.css` files, which I intentionally configure it to build inside the same folder as the `.scss`. I _could_ choose to have CodeKit also minify my javascript, but I don't really care to do so. I much prefer to be able to read the scripts my websites are running, for debugging purposes. And I optimize the few images that my sites use as part of their themes myself (the rest of the images which appear on my sites are uploaded by the users). Though It would actually be nice to have CodeKit optimize them automatically. I'll look into that.

But I can't think of any reason that CodeKit would care _at all_ about any of the other files in my project. Especially the python code, or the `Dockerfile`, or `.conf` files for the programs that run inside the Docker container.

I've known for a while that CodeKit really isn't written for developers like me. I mean, the entire "browser preview" functionality is utterly baffling to me, because I don't write HTML files for direct display. I write loads of HTML, but it's all django templates, which can't be rendered by a third party service. But the CodeKit functionality that didn't work for me also didn't get in my way... until recently. 

I'd honestly use something else, if I knew of a single Mac app that did automatic Sass and Less compiling anywhere near as well as CodeKit does it. I used `Less.app` back in the day, and upgraded to CodeKit when you first created it. My code shop switched to Sass a few years later, but we still have legacy apps which use Less, and CodeKit's ability to auto-compile both is a godsend.

**Comment by bdkjones** [comment]
With source maps, you need not worry about seeing minified javascript in the browser’s inspector—you‘ll see the original source, just like source maps show the original Sass instead of the compiled CSS.

In your case, simply flipping the Output Action to “ignore” for languages other than Sass and Less should give you what you’re looking for.
