### ISSUE TITLE
import error with if statement

### ISSUE THREAD

**Issue by Gloosecap** [bdkjones/CodeKit#566]
Hi,

In main.js I am importing jQuery: import $ from 'jquery'; but on a few pages jQuery loads separately in the head and I don’t want to import it in main.js. So I’ve tried:

```
if(window.jQuery)  {
	console.log("jQuery already loaded");
	} else {
	console.log("jQuery imported");	
	import $ from 'jquery';
}
```

But that gives an error: 'import' and 'export' may only appear at the top level. If I remove: import $ from 'jquery'; from the if statement and replace it with the jQuery library it works, but I want to keep main.js uncluttered.  

What would be the correct way to achieve this? 

Thanks

**Comment by bdkjones** [comment]
This isn’t a CodeKit issue. You’re seeing that error because the JavaScript standard allows imports only at the top of a file. The correct approach is to restructure your JS for the website so that you don’t have to do this jquery check at all. Either bring jquery in with a separate script tag in the <head> element of pages that need jquery, or create more modular JS files that import jquery when needed.

**Comment by Gloosecap** [comment]
Thanks for the answer Bryan. I'm working on the modular approach that you suggested.
