### ISSUE TITLE
Rollup prepending function name with "_"

### ISSUE THREAD

**Issue by macfire** [bdkjones/CodeKit#570]
**Quick, short summary:**
When exporting to IIFE, the exported function name is prepended with an underscore "_".

**Expected results:**
Function name should match file name.

**Actual results:**
Example:

```javascript
// Source code
// MyTest.js

export default MyTest = function () {

      const log_it = function(_msg) {
          let msg = _msg || "No message";
          console.log(msg.toString());
      };

      this.init = function(msg) {
          log_it(msg)
      }
};
```

```javascript
// Build code
// MyTest.js

var _MyTest = (function () {
      'use strict';

      var MyTest$1 = MyTest = function () {

            const log_it = function(_msg) {
                let msg = _msg || "No message";
                console.log(msg.toString());
            };

            this.init = function(msg) {
                log_it(msg);
            };
      };

      return MyTest$1;

}());

```
**Exact steps to reproduce:**
Using ES6 Bundle Format:  IIFE
(no minification or transpiling)

***
Operator error on my part?
RollupJS issue?

It seems this behavior started a month or so ago.
Previously working projects are now having the variable names changed.

**Comment by bdkjones** [comment]
I noticed this as well, but it’s definitely coming from Rollup. CodeKit does not add the underscore.

**Comment by bdkjones** [comment]
I did not consider it a breaking issue because the function is immediately invoked and the names reference to it should therefore not matter much.

**Comment by macfire** [comment]
I'll check with RollupJS.

It breaks access in the sense that I have to change code that calls that function.

Example:
```javascript

var my_test = new MyTest();
my_test.init("hello");
/* ERROR:  Cannot find variable MyTest */

var my_test = new _MyTest();
my_test.init("Oh, there you are.")
/* works, but I have to change code that is looking for MyTest() */

```
Maybe I'm using RollupJS in a way that is not intended.
Or am missing another step.

**Comment by macfire** [comment]
I installed Rollup to test from command line.
I'm not able to replicate the issue.

If I specify the name of output function, it works as expected:
Example:
```bash
$ rollup src/MyTest.js -f iife --name MyTest

src/MyTest.js → stdout...
var MyTest = (function () {
      'use strict';

      var MyTest  = function() {

            const log_it = function(_msg) {
                let msg = _msg || "No message";
                console.log(msg.toString());
            };

            this.init = function(msg) {
                log_it(msg);
            };
      };

      var MyTest$1 = MyTest();

      return MyTest$1;

}());

```

If no name is specified, then the output is a IIFE that cannot be accessed from without.

```bash
$ rollup src/MyTest.js -f iife

src/MyTest.js → stdout...
(function () {
      'use strict';

      var MyTest  = function() {

            const log_it = function(_msg) {
                let msg = _msg || "No message";
                console.log(msg.toString());
            };

            this.init = function(msg) {
                log_it(msg);
            };
      };

      var MyTest$1 = MyTest();

      return MyTest$1;

}());
(!) If you do not supply "output.name", you may not be able to access the exports of an IIFE bundle.
```

**Comment by macfire** [comment]
@bdkjones  Have you decided if this is a "will fix" or "won't fix" issue? 
I can work around the current issue temporarily, but I'm trying to decide how to proceed longer term. A lot of my code is breaking when I recompile previously working projects.

Thanks.

**Comment by bdkjones** [comment]
As far as I know, this is a Rollup issue. CodeKit passes the name of the file (sanitized to remove illegal characters) as the module name. It was working totally fine before the last Rollup update and I haven’t changed anything on my end. If the issue IS mine, I’d certainly want to fix it. But I don’t see how I can be causing this.

**Comment by macfire** [comment]
Ok, I'll proceed with posting issue with Rollup.

**Comment by bdkjones** [comment]
It would be a good idea to verify that it happens with Rollup outside of CodeKit.

**Comment by macfire** [comment]
From the command line, I can't replicate with Rollup (i.e. outside of Codekit).

See above https://github.com/bdkjones/CodeKit/issues/570#issuecomment-549088700

**Comment by bdkjones** [comment]
can you put together a small demo project that replicates the issue? I need to isolate variables. For example, are you also transpiling with Babel in the CodeKit project where this is happening? Turn off Babel to isolate rollup. And turn of minification to eliminate that as a possibility.

**Comment by macfire** [comment]
Simple demo project
[rollup_test.zip](https://github.com/bdkjones/CodeKit/files/3842681/rollup_test.zip)

By the way, how can I find out what version number of Rollup is used in CodeKit?

**Comment by bdkjones** [comment]
Oh for Christ's sake. I figured it out. It's because Swift is godawfully retarded with Strings.

The old Objective-C String interface was absolutely wonderful to work with. You could simple things like, "Tell me what the 4th character of the string is." And it would say, "here you go."

And then some idiot hipster devs at Apple threw a fit and said, "BUT WHAT IF SOMEONE USES AN EMOJI AND THAT EMOJI HAS MULTIPLE CODE POINTS!?" And because there wasn't an adult in the room to say, "Well, humans treat emoji like a single character. So even though it takes up multiple codepoints, it should still be only one character," we now have to do shit like this:

            // The first character of a JS identifier MUST be alphabetic or $ or _.
            let character = filename.first!
            let scalarValue = character.unicodeScalars.first!

We can't just use the letter `R`, which is what `character` is in your demoProject. Oh god no. That would be far too elegant for Swift. We have to convert that letter into a UnicodeScalar. What is a UnicodeScalar, you ask? Great question. Moving on.

See, the `CharacterSet` class has a function named `doesContain()` which will accept any object. So if we had a `CharacterSet` of allowed characters, we could do this:

    // Assume 'myAllowedCharacters' contains all possible letters.
     let isAllowed: Bool = myAllowedCharacters.doesContain(character)

You'd think this would work, right? It would! In Objective-C. But this is Swift! And if you're going to write Swift, you better think like a goddamn compiler engineer because that's who built the language. So now we have to do this:

    let isAllowed: Bool = myAllowedCharacters.contains(scalarValue)

And now it works.

There are things I like about Swift. And then there are times I want to punch everyone who had anything to do with creating Swift. It's a great programming language ruined by too-smart-for-their-own-good programmers.

**Comment by bdkjones** [comment]
</rant>

At any rate, this is fixed for the next update. Thanks for your patience.

**Comment by macfire** [comment]
Thanks much!

**Comment by macfire** [comment]
Downloaded new update. Thanks for fixing.
