### ISSUE TITLE
Can't compile scss files (compass project)

### ISSUE THREAD

**Issue by asaadmahmood** [bdkjones/CodeKit#573]
**Quick, short summary:**
I have a compass project that I just created (the issue also reproduces on old compass projects). I try to save a scss file, and I get an error in the compiler.

This issue was not happening prior to my update to Catalina, and happened after the update.

**Expected results:**
The css is compiled without any errors.

**Actual results:**
![Screenshot 2019-11-21 at 2 32 25 PM](https://user-images.githubusercontent.com/11034289/69325385-e3bbef80-0c6b-11ea-8946-3316c9234de7.png)

**Exact steps to reproduce:**
Save any scss file.

**A link to download a simplified project or file that shows the issue:**
[Baba.zip](https://github.com/bdkjones/CodeKit/files/3873932/Baba.zip)

**Your configuration (any details about your system that you think might be relevant)**
Mac OS Catalina. Currently on 10.15.1 (19B88).

**Comment by bdkjones** [comment]
Compass was end-of-lifed several years ago and will no longer compile on Catalina because it relies on Ruby Sass. Ruby is such a godawful slow language that it had to cache work to disk so subsequent compiling could be a little faster. In Catalina, the disk root where Ruby Sass attempts to write that cache is now read-only, so it fails. 

Remove Compass from your project and compile with Libsass. If you’re looking for similar mixins, try Bourbon.
