### ISSUE TITLE
Compiling failed with this error: Errno::EROFS on line ["239"]

### ISSUE THREAD

**Issue by sanseistone** [bdkjones/CodeKit#577]
Sorry, I'm having trouble compiling SCSS.
The error message is as follows:

> Compiling failed with this error: Errno::EROFS on line ["239"] of /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb: Read-only file system @ dir_s_mkdir - /.sass-cache
> Run with --trace to see the full backtrace

> my computer:
> Mac mini (2018)
> 
> operating system:
> macOS Catalina 10.15.2 (19C57)

Not sure if it is the cause of the T2 chip of the apple computer, the security mechanism is very high, and the permission problem is caused.
Hope to solve the problem as soon as possible, thank you.

**Comment by bdkjones** [comment]
Welcome to Catalina, the shittiest OS to come out of Cupertino ever.

You need to enable Libsass in Project Settings > Sass. If that option is greyed out, you need to remove Compass from your project completely, then refresh it in CodeKit (or remove and re-add it) and then enable Libsass. Compass was discontinued years ago.

The Ruby compiler tries to write cache files to the disk root to make it seem faster because Ruby is godawful slow. In Catalina, the disk root is no longer writable.
