### ISSUE TITLE
WordPress Stylesheet Directory Issue on Default Port (80)

### ISSUE THREAD

**Issue by markvanwijnen** [bdkjones/CodeKit#579]
**Quick, short summary:**
When a WordPress custom theme directory is being monitored with CodeKit (config.codekit3) and you host the website on a default port (80) and watch the website through the CodeKit Preview Server the stylesheet directory suddenly changes to the name of the local machine and therefor no resources can be found.

**Expected results:**
In the index.php file with the code `echo get_stylesheet_directory_uri();` an output of:
http://**local-machine**:5757/wp-content/themes/**theme-name**

**Actual results:**
In the index.php file with the code `echo get_stylesheet_directory_uri();` an output of:
http://**local-machine**:5757/wp-content/themes/**local-machine:5757**

**Exact steps to reproduce:**

1. Host [WordPress](https://wordpress.org/download/) with MAMP on the default port 80. The issue does not occur on custom ports. However port 80 is required to use WordPress Multisite.
2. Create a theme name it whatever and only put the essentials in `index.php` and `style.css`. ([More information about creating the style.css](https://developer.wordpress.org/themes/basics/main-stylesheet-style-css/)) 
3. In the `index.php` file you will only put one line of code:
`<?php echo get_stylesheet_directory_uri();`
4. Add the "whatever"-theme folder to the CodeKit Projects.
5. Go to CodeKit > Settings > Project Settings > Browser-Refreshing.
6. Go to the "External Server Options"-section and turn on "Use An External Server".
7. Make sure the "External Server Address" points to the proper location with or without the port 80 added doesn't matter.
8. Click on the green round button at the top of the CodeKit-window (right next to the minimize, maximaze, close buttons of the window). In the dropdown choose one of the options. For example the Bonjour-address.
9. A new window will open with the actual results, which is the issue.

**A link to download a simplified project or file that shows the issue:**
This is mainly local on my development machine. But you can easily create it yourself with the above steps.

**Your configuration (any details about your system that you think might be relevant)**
- MAMP Pro version 5.5.1
- CodeKit version 3.10.2 - Build 31934
- WordPress version 5.3.2

**Comment by bdkjones** [comment]
The issue here is that you've named your theme the same as the external server address. 

When CodeKit functions as a reverse proxy server (when you enable the External Server option in Project Settings), the app scans every page for all occurrences of the external server address and replaces those with the proxy server address. 

For speed, this process is done via simple find-and-replace; the page is not parsed and no heuristics are done to decide whether an occurrence of the external server address is a link or not. 

The solution is to make sure your theme name/directory does not conflict with the external server address name.

**Comment by bdkjones** [comment]
Also: Excellent writeup. Thanks for all the detail and the time spent doing that!
