### ISSUE TITLE
Feature request: Allow legacy @codekit-prepend on top of ES6 bundles

### ISSUE THREAD

**Issue by Ariane-B** [bdkjones/CodeKit#589]
Sometimes, there's an unfortunate case where we have a project fully functional with ES6 bundling, but in the end we have to add an old script that doesn't work with bundling at all -- old code from a NPM/Yarn module that works by setting all kinds of variables, where importing it as an ES6 side-effect module won't do. Using both will throw the error:

> This file contains both modern ES6 'import' statements and legacy '// @codekit-prepend/append' statements. It cannot be processed with both.

It would be useful in those cases if we were allowed to simply prepend the script to the rest of our bundle, and use its global variables and functions as the old module's documentation dictates.

I'm not saying it's a good idea to structure a project with both ES6 bundling and legacy statements. It's a mess. But sometimes, between a mess and having to copy someone else's potentially unclear code to your folder and refactor it, you have to choose the former.

**Comment by bdkjones** [comment]
Yea, so the issue here is that there are all sorts of scenarios where this could break or result in unusable code.

The bundler, for example, rearranges items and wraps them in IIFEs for the browser. Merely pasting some javascript ahead of other Javascript won’t deal with this fact and thanks to variable hoisting, you’re likely to get all sorts of shadowed variables and similar collisions. 

While this might not occur in *every* case, it would occur in enough of them that it was not prudent to offer the functionality. In addition, source maps wouldn’t be able to handle the old @codekit-prepend statements and would be totally broken.

Finally, it would also have carried the legacy @codekit-prepend statements forward as an officially recommended way of combining files. Those statements were created in 2011—almost a decade ago—when Javascript had no official capacity for combining files. Now that it does, I want to encourage people to adopt that approach rather than a proprietary CodeKit solution. It has always been my intent to endorse standards whenever possible and fall back to proprietary solutions only when nothing else exists.

The clean way to deal with this is to take the legacy JS and simply give it its own <script> tag until you can eliminate that dependency.

**Comment by Ariane-B** [comment]
Thank you. I appreciate the thoughtful answer. This has a lot more implications than I thought.
