### ISSUE TITLE
[Feature Request] Direct Support for Tailwind

### ISSUE THREAD

**Issue by luxlogica** [bdkjones/CodeKit#593]
Low-level, utility-first CSS libraries like **[Tailwind](https://tailwindcss.com)** are becoming increasingly popular, as they help to greatly reduce the size and maintenance of CSS stylesheets. Tailwind is arguably the most famous and widely-used, having been adopted by companies like GitHub, Heroku, Kickstarter, Twitch, Segment, and others. You can read an explanation of its 'utility-first' approach [here](https://tailwindcss.com/docs/utility-first/). In short: it makes large&complex web projects much more manageable, and it makes plain&simple projects stupidly easy - sometimes not requiring you to write any CSS at all. 

Tailwind can be used as a Node command-line tool, or as a PostCSS/Webpack/Gulp/Grunt plugin. The workflow is:
1. add Tailwind to your project via npm
2. (optionally) create a config file, to suit your theme/settings for your project
3. import the Tailwind auto-generated classes into your CSS file, by using its custom `@tailwind` directives
4. process your CSS file with Tailwind - it will process any Tailwind-specific directives it finds in the file, like the `@tailwind` and `@apply` directives, and generate the production CSS file you should include in your html.

Right now, the easiest way to use libraries such as Tailwind with CodeKit is to:

1. install Node & friends directly on your Mac
2. add Tailwind to your project via CodeKit, and optionally create a config file
3. In CodeKit, go through the process of defining an **'other' language** - to process CSS files using an arbitrary extension, eg., '.twnd'.
4. In CodeKit, go through the process of defining a **hook** to process your Tailwind _'.twnd'_ files.
5. Create you project's CSS file with the extension '.twnd', and CodeKit will process it.

Ideally, it would be great if Tailwind could be incorporated *directly* into CodeKit as a CSS post-processor, so that the user would not need to install Node, nor define new language extensions and/or hooks. 

Tailwind would be a *processing option* for the CSS language: in 'CSS Options', under the 'Other Options' setting, we could just have another tick box for 'process with Tailwind'. We could then also have a 'Tailwind' entry under 'Tools' - along with 'Babel', 'Rollup', etc. - to allow the user to change any needed defaults.

Note that as it is a CSS post-processor, Tailwind can also work [alongside CSS preprocessing languages](https://tailwindcss.com/docs/using-with-preprocessors), like Less, Sass and Stylus - so in theory we could have the same 'process with Tailwind' option added to those languages, too.

**Comment by xcrap** [comment]
This would actually be amazing, or just adding better support for PostCSS plugins, but the way the project is... It's already difficult having updates for the basic components :\

**Comment by perry-garvin** [comment]
Agree. This would be great.

**Comment by iocouto** [comment]
Perhaps Tailwind could be added as a 'framework'? 

This might be easier to implement than treating it as a 'preprocessor'. The current version of Tailwind is highly opinionated, encouraging users to adopt a very specific set of tools - e.g., discouraging users from using the 'tailwind' command for production builds, encouraging users to adopt PostCSS instead of LESS/SASS, and to use PurgeCSS as a toolchain module, all of which might make it harder to just 'plug it in' as a preprocessor.

**Comment by bdkjones** [comment]
> all of which might make it harder to just 'plug it in' 

This is pretty much the entire description of what CodeKit solves. EVERYTHING I integrate is hard. Hell, there's parts of CodeKit that bend over backwards to make Compass work.

The good news is that direct support for Tailwind is coming. I'm working on it now. I AM adopting the opinionated flow from the official Tailwind docs, though, because that really seems like the "correct" way to use Tailwind.

As a side effect of the massive re-architecting involved to support Tailwind, CodeKit will have better integration with custom PostCSS plugins and config files as well as built-in support for PurgeCSS in the UI (regardless of whether you're using Tailwind or not). Can't wait for all the angry emails about how CodeKit is broken because such-and-such CSS rule isn't showing up and of course it MUST be the case that the app is broken; it can't possibly be that I misconfigured PurgeCSS!

**Comment by bdkjones** [comment]
This is going live in CodeKit 3.14. It's all automatic, but you can still customize tailwind as wanted. Look for the screencast and docs in the release notes when 3.14 is out.

**Comment by xcrap** [comment]
Guess it’s time to return to Codekit again :)

**Comment by perry-garvin** [comment]
fire emoji
