### ISSUE TITLE
[Feature Request] Direct Support for PurgeCSS

### ISSUE THREAD

**Issue by luxlogica** [bdkjones/CodeKit#594]
**[PurgeCSS](https://purgecss.com)** is a tool that analyses the HTML, JS and CSS files in your project, and removes the unused CSS styles from your compiled final CSS file  - thereby *greatly* reducing its size, specially if using frameworks like Bootstrap, Foundation, UIKit, or libraries like Tailwind - which generate thousands upon thousands of unused styles. PurgeCSS can be used as a Node command-line tool, or as a Webpack/PostCSS/Gulp/Grunt plugin. 

For a comparison between PurgeCSS, PurifyCSS and UnCSS, please see [this page](https://purgecss.com/comparison.html) in their docs.

Using PurgeCSS, the CSS stylesheet for the Firefox Send site was reduced from 600kb+ to 13kb. Sample configuration and usage:
* Medium article showing how to use [PurgeCSS with Bootstrap](https://medium.com/dwarves-foundation/remove-unused-css-styles-from-bootstrap-using-purgecss-88395a2c5772)
* directly from the Tailwind docs, instructions on how to use [PurgeCSS with Tailwind](https://tailwindcss.com/docs/controlling-file-size)

Ideally, it would be added as a 'purge compiled CSS' tick box under the 'Options' settings for CSS-based languages, like Less, Sass, Stylus, and CSS itself. PurgeCSS could then be added also to the project settings as a 'Tool' - along 'Babel', 'Rollup', etc. - for more detailed configuration, if needed, on a project-by project basis.

**Comment by bdkjones** [comment]
Yea, I'm aware of PurgeCSS. 

The reason I haven't incorporated it to date is that it can also introduce REALLY subtle bugs and problems with your website that aren't immediately apparent and may make it all the way to production. For example, if you have JavaScript that's injecting unique styles to an element in response to an event by adding a class to that element (say, `form-field-failed-validation`), PurgeCSS will completely remove the styles associated with `.form-field-failed-validation` because it does not see them in use on your HTML pages. To prevent that, you have to manually tell PurgeCSS not to remove those styles and then remember to do that all over the place.

Here's how that plays out for me, historically:

Me: *wakes up* 
Me: "Let me just check my email."
Some User: "WHY THE FUCK IS YOUR APP BROKEN I'VE BEEN TRYING TO COMPILE MY SASS FOR FIVE FUCKING HOURS AND CODEKIT IS DELETING SOME CLASSES RANDOMLY AND IF I RUN THE SASS COMPILER ON THE COMMAND LINE THAT DOESN'T HAPPEN WHY ARE YOU SUCH A SHITTY DEVELOPER?"

That's not an exaggeration. I save the best emails I get. The FIRST thing people conclude when something isn't working the way they think it should be working is that it's my fault and CodeKit is trash.

Given that, you can see what I'm slow to introduce tools that are likely to be problematic unless the user is an expert at configuring them. The last time I looked at PurgeCSS for inclusion, there was some discussion that they were going to try to start parsing JS files to detect when styles are being added dynamically. My decision at the time was to allow that to develop so I wouldn't have to put the burden of configuration on users (and my inbox wouldn't be filled with angry people who think I'm a moron).

Has PurgeCSS evolved to that point?

**Comment by luxlogica** [comment]
Totally get your point. I think the main issue there is that people start using tools without fully understanding how those tools process and affect their code - and this is why making it _optional_ would be the safest way to introduce it.

This particular issue (with dynamically-generated class names) has been really well-documented - for example, have a look at **[this page](https://tailwindcss.com/docs/controlling-file-size)** in the TailwindCSS docs - in specific, the 'Writing purgeable HTML' section. It teaches users how to get around this issue - the solution is really, really simple, and it boils down to ONE RULE: **don't use string concatenation to create your class names**. We can find the same advice in the PurgeCSS docs, as well as in the docs of other projects that use it.

The example from the Tailwind docs is:

``` html
<!-- DO NOT DO THIS - your class names are not being explicitly shown here -->
<div :class="text-{{ error ? 'red' : 'green' }}-600"></div>

<!-- DO THIS INSTEAD - class names appear explicitly in your markup/code -->
<div :class="{{ error ? 'text-red-600' : 'text-green-600' }}"></div>
```

PurgeCSS has made the decision to remain a 'dumb' tool _on purpose_ - specifically so that issues like these are easy to solve. There are other tools that take a different approach, and try to evaluate the javascript file, to get the classes that are generated at runtime. That can lead to a world of pain of its own. PurgeCSS' approach is IMHO the most sane, and safe. 

Note that because of this 'dumb parsing' approach, PurgeCSS is able to handle a multitude of file types - not just html and js. Because it's basically just (dumbly) parsing text, you can throw anything at it - pug/haml templates, vue components, etc. - and as long as you follow that ONE RULE, you should be good!

IMHO the benefits that most CodeKit users will get from PurgeCSS far outweigh the inconvenience of some obnoxious idiots - but that's easy for _me_ to say, 'cause I don't have to answer those annoying emails... But perhaps a simple note in the CodeKit docs about the ONE RULE might be all you need to make these dimwits look foolish. ;-)

**Comment by luxlogica** [comment]
Just noticed that the latest versions of Tailwind now include PurgeCSS automatically.

**Comment by bdkjones** [comment]
This is going live in 3.14 soon. It'll be available for all stylesheet languages.
