### ISSUE TITLE
[CK4 Suggestion] Remove Non-CodeKit Frameworks

### ISSUE THREAD

**Issue by luxlogica** [bdkjones/CodeKit#595]
This is a suggestion to try and perhaps help make the CodeKit interface - and maintenance - simpler. Perhaps something worth considering for CodeKit 4...

Some of the 'frameworks' listed in CodeKit are abandoned - like Compass, and Neat. Others haven't seen an update in well over a year. Then, it always seemed a bit arbitrary to me that Foundation gets included in CodeKit, but not Bootstrap, nor UIKit, nor Bulma, nor Semantic UI, or any number of others. And the truth is, that all those can already be installed by CodeKit as npm packages anyway - so that entire section in our Project Config is starting to feel a little outdated, and redundant. 

On the other hand, with the proliferation of low-level utility CSS libraries - like Tailwind - and component-based javascript development libraries - like Vue/Svelte/Alpine - I see an even bigger role for custom **CodeKit Frameworks**. 

So, my suggestion is:
  * remove the entire 'Frameworks' section of the Project Config, and stop bundling those frameworks/libraries/tools by default
  * retain the explicit setting for 'CodeKit Frameworks' - but that could be moved into the 'Project Settings' section

**Comment by bdkjones** [comment]
I hold backwards-compatibility in very, very high regard. Yes, Compass is dead. CodeKit will warn you if you try to start a new Compass project. But, that client site you built seven years ago using it will still compile perfectly when the client needs a tiny change made.

I don't like the JS world's constant "Fuck that thing we told you to use two months ago. That thing is rubbish. THIS thing is what you should be using!" approach to development. If I put something in CodeKit, I intend to support it for a long, long time so that folks can rely on the app and feel safe installing updates. For example, when I rewrote a huge swath of the app to support npm last year, I also brought Bower along for the ride. It would have been insanely easier to just drop it. It would have saved me a ton of work. But it would have stranded a lot of user projects and forced many of them to do a ton of work they didn't want to do to migrate ancient projects to npm.

It has always impressed me how Apple STILL, to this day, carries APIs in macOS that were deprecated in 2004. They still work. That kind of stability and reliability is virtually unheard of anywhere and it's something I strive for with CodeKit.

As for the first-party frameworks integrated into the app, I do that based on demand. Tailwind has come up frequently, so it's something I've got on my list.

**Comment by luxlogica** [comment]
Truly appreciate how much you look after us, your users. ❤️ 

Would it be possible to keep the compatibility, so that the users that need it would still get it, but remove these items from the interface? Perhaps we could encourage these users to 'migrate' their projects to using npm?

Just trying to see if there is a way to make the interface cleaner - and your life easier! :)

**Comment by bdkjones** [comment]
Yes. I have considered showing Compass only when a Compass project is active, and so forth. Trying to get users to migrate from Bower to npm isn't worthwhile—the app defaults to npm and the folks using Bower are very well aware that it's end-of-lifed. They're mostly working on old projects that aren't worth migrating to newer package releases (and retesting, redeploying, etc.) They have clients who need updates to ancient sites. Maybe they just need to install an old bower package real fast to do something new and they have absolutely no budget to switch to npm and spend time re-configuring everything.

My general rule has been that once I add something in CodeKit, I keep it around as long as that thing itself it still online. When bower finally shuts off its website and the registry and all that, I'll remove it from the app. 

The Frameworks don't really suck up much of my time. Most of them are insanely simple—they're just file includes. (Compass was definitely NOT simple; supporting that was a crazy amount of work and workarounds, which is why various competitors that came and went over the years such as Hammer never offered Compass support.) But that's all a sunk cost now.

Zurb Foundation is a pretty straightforward process. Behind the scenes, CodeKit just clones the Foundation repo with git, runs `npm install`, nukes a few files from the result (gulp config files, etc.), then refreshes the project and sets a few files to have Output Paths in the correct spot (regardless of your default Project Settings) and turns on the appropriate compiling steps for critical files.

**Comment by luxlogica** [comment]
I love the idea of the 'deprecated' parts of the interface being hidden, unless it's an old project that needs it. That would mean that CodeKit would feel modern to current and new users, and would still retain compatibility with the old ones. 

It's wonderful that you provide such great built-in support for Foundation, but the danger here is that it looks like you're promoting Foundation over others. If it's easy enough to provide 'one-click installer' support for other frameworks, then I'd suggest also including at least a few others, such as Bootstrap (the most popular), **[UIKit](https://getuikit.com)** (arguably the most feature-full, and most stable, and LESS-based) and Bulma (no-javascript, extremely modular and extendable). But IMHO, if removing frameworks would save you work, you certainly have my blessing to remove it - it's easy enough for us to install them as npm packages already, and I'd rather you spent your time with things like PurgeCSS and Tailwind! ;-)

**Comment by bdkjones** [comment]
This is underway. I've nuked Compass and Neat from the UI, although both are still invisibly part of CodeKit so that old projects that rely on them will compile just fine.
