### ISSUE TITLE
Dart Sass support: ETA?

### ISSUE THREAD

**Issue by Ariane-B** [bdkjones/CodeKit#598]
Related: 

Today, I learned that going forward, `@import` statements [are going to be deprecated](https://sass-lang.com/documentation/at-rules/import) in favour of the new `@use`.

I was doing some Sass refactoring anyway, so I thought I'd future-proof our code right away by switching everything over to `@use`. But here's the thing: `@use` [is not yet supported](https://sass-lang.com/documentation/at-rules/use) by either the Ruby Sass or Libsass compilers, so as long as I compile with CodeKit, it seems I can't.

They're working on it, but in the mean time, it's a weird situation to be in to know something is going to be deprecated at some point but not being able to use the recommended version.

Going by issue #246, it seems you like the idea of Dart Sass. Are there challenges preventing its implementation in CodeKit soon?

**Comment by bdkjones** [comment]
Nope. DartSass is already implemented and will be going live this weekend, hopefully.

Libsass will remain the default because it still MUCH faster. The Libsass crew is working on `@use` support. Sass also has a very good history of steady, reasonable deprecation (thanks to @nex3). They do not simply drop features or syntax without giving the ecosystem a long time to migrate. I *highly* doubt that `@import` will be dropped before Libsass has implemented, tested, and shipped support for `@use`. Doing that would be extremely out of character for Sass.

**Comment by Ariane-B** [comment]
I see. Thank you very much! I appreciate the (blazingly fast) response. In light of that, I think I'll calm down and wait for Libsass's `@use` implementation.

**Comment by nex3** [comment]
> Libsass will remain the default because it still faster.

This is only true if you're running the JS-compiled version. When running the standalone executables available from GitHub, [Dart Sass is about on par with LibSass](https://github.com/sass/dart-sass/blob/master/perf.md).

> The Libsass crew is working on `@use` support.

As far as I know, no work is currently underway to support `@use` in LibSass.

> I _highly_ doubt that `@import` will be dropped before Libsass has implemented, tested, and shipped support for `@use`.

In the [module system proposal timeline](https://github.com/sass/sass/blob/master/accepted/module-system.md#timeline), we outlined plans for what happens if LibSass does or does not implement `@use` in time. This proposal is of course subject to change, and we definitely want to give the ecosystem plenty of time to migrate, but we can't block the deprecation of `@import` on LibSass *forever*.

**Comment by bdkjones** [comment]
@nex3 thanks for the update! I looked at `perf.md` and it looks like the VM version of DartSass is the way to go, despite the extra space it’ll take. (CodeKit is already 250mb thanks to all the node_modules it bundles.)

The primary blocker on making it a default is a lack of support for custom functions. I’ve had TONS of people (rightly or wrongly) ask for Glob support in Libsass, so I wrote my own handlers for it and added them.

Likewise, I’m about to add a `url64()` function to auto-base64-encode images. To my knowledge, these things can’t yet be done with DartSass. If I made DartSass the default, I’d have to deal with probably 200 emails asking why globbing is suddenly broken.

**Comment by nex3** [comment]
One easy solution would be to write your custom importer and function in Dart, compile that to a standalone executable, and ship it. You could also check out [the embedded protocol](https://github.com/sass/embedded-protocol) and [embedded Dart Sass](https://github.com/sass/dart-sass-embedded) if you didn't want to write Dart code.

**Comment by Ariane-B** [comment]
What I'm about to say may be ridiculous as I know next to nothing about making apps, but if the size of CodeKit is starting to be prohibitive, could it be possible/advisable to split it up somehow?

Like, you could have a "vanilla" modules handler that would update those separately, and CodeKit itself that would interact with it. So when you ship a new version of CodeKit with new features, it wouldn't necessarily include the whole modules pack. And similarly, when a module updates, it wouldn't need to come with all of CodeKit.

There's probably a good reason you're bundling it all in one package, but I thought I'd try my shot anyway.

**Comment by bdkjones** [comment]
@nex3 The Dart API link at https://sass-lang.com is 404-ed and although another part of the website links to the GitHub readme and says to look for the Dart API, there is no mention of it. The readme has info only on the JavaScript API.

I'm not opposed to attempting a globbing function in Dart, but I can't find any live links to API documentation.

On the other hand, that embedded protocol looks...difficult. Reminds me of kernel-level programming, where buffers and padding and endianess prevail.

**Comment by bdkjones** [comment]
@nex3 Interestingly, Apple does offer a Swift protocol buffer plugin: https://github.com/apple/swift-protobuf (I'm attempting to gradually move CodeKit to Swift because Apple has made it very clear that's their future.)

It would introduce some middleware between Sass and CodeKit—the Swift plugin requires a runtime library and it has 39 open issues. There's the potential for bugs out of my control to interfere.

What is the expected performance overhead of using Protocol Buffers to handle glob import statements and a custom `url64()` function vs doing those things via the Dart API? If the performance of the Protocol Buffer approach is going to be on par with the JavaScript API, for instance, the latter approach would be easier and involve no extra middleware for me to worry about.

**Comment by bdkjones** [comment]
@nex3 And one more question: is Embedded Sass going to be actively maintained and remain on par with DartSass? In other words, I'm worried that all the Webpack/Grunt/Gulp/YaddaYadda implementors will simply use the JS implementation and the Embedded Sass protocol won't be updated timely as Dart Sass evolves and adds new features, simply because there's not much demand for it. That'll leave me hurting if I invest in that approach today.

**Comment by bdkjones** [comment]
@nex3 I explored the Embedded Sass protocol, but if I'm reading the `protoc`-compiled source right, it does not look like this can be used to support globbing because the compiler is expecting an `importResponse` that assumes the import resolves to a single file. It looks like I'm supposed to either send back the content of the file or the path to it on disk.

There's no way (that I see) to pass a **list** of files that the import statement resolves to, as I do with Libsass. That said, the docs are a little sparse and I *did* see the comment that "all sass values are lists" somewhere in there. Looking at the generated API from `protoc`, however, I don't see a way to send back multiple resolutions for a single `@import`.

**Comment by bdkjones** [comment]
@nex3 It doesn't look like it's even possible with the JS API right now. According to https://sass-lang.com/documentation/js-api#importer, the importer function must return an object with the key `file` that contains **a** path to the resolved file on disk. There is no indication that a `list` is acceptable here.

**Comment by nex3** [comment]
> The Dart API link at https://sass-lang.com is 404-ed and although another part of the website links to the GitHub readme and says to look for the Dart API, there is no mention of it. The readme has info only on the JavaScript API.

Can you file an issue for this at https://github.com/sass/sass-site?

> I'm not opposed to attempting a globbing function in Dart, but I can't find any live links to API documentation.

The Dart team changed URLs without setting up redirects :angry:. The real API docs are [here](https://pub.dev/documentation/sass/latest/sass/sass-library.html).

> On the other hand, that embedded protocol looks...difficult. Reminds me of kernel-level programming, where buffers and padding and endianess prevail.

A protocol buffer library will shield you from *most* of that, but yeah it's on the low-level end of things.

> What is the expected performance overhead of using Protocol Buffers to handle glob import statements and a custom `url64()` function vs doing those things via the Dart API? If the performance of the Protocol Buffer approach is going to be on par with the JavaScript API, for instance, the latter approach would be easier and involve no extra middleware for me to worry about.

We don't have hard numbers yet, but I'd expect embedded Sass to be substantially faster than Sass-in-JS and slightly slower than doing everything in Dart. The slowdown will presumably be proportional to the number of calls that need to be made across the executable boundary, so a Sass project will a bunch of glob imports and `url64()` calls will be slower than one that just uses vanilla functionality.

> And one more question: is Embedded Sass going to be actively maintained and remain on par with DartSass? In other words, I'm worried that all the Webpack/Grunt/Gulp/YaddaYadda implementors will simply use the JS implementation and the Embedded Sass protocol won't be updated timely as Dart Sass evolves and adds new features, simply because there's not much demand for it. That'll leave me hurting if I invest in that approach today.

I can't predict the future perfectly, but I can say that it's our *intention* to maintain the embedded protocol for a long time. It's essentially Dart Sass's means of making itself available to many different languages, in the same manner as LibSass's C API. In fact, it's possible that the embedded protocol will outlast Dart Sass itself—once we have embedded hosts in a bunch of languages, we 
can easily reimplement the compiler without changing all those downstream plugins as long as the new compiler also speaks the protocol.

> It doesn't look like it's even possible with the JS API right now. According to https://sass-lang.com/documentation/js-api#importer, the importer function must return an object with the key `file` that contains **a** path to the resolved file on disk. There is no indication that a `list` is acceptable here.

Through the JS API, you'd need to return a `{data}` object that contains a synthetic file with all the `@import` statements for the real files you want to load. That's likely to be true for Dart Sass and the embedded protocol as well, for what it's worth.

**Comment by bdkjones** [comment]
@nex3 The `{data}` object with all the imports stacked up is clever. I would not have thought of that. 

I've got Dart Sass implemented and decided to go with the fastest option: the Dart VM. I'll hold off on globbing support for now because with the new `@use` syntax and the ability to target specific elements with it and pass configuration, I'm not sure globbing will remain as popular as it has been.
