### ISSUE TITLE
Dart Sass deletes the CSS on error; hard refresh often required

### ISSUE THREAD

**Issue by Ariane-B** [bdkjones/CodeKit#610]
Hi!

Since switching to Dart Sass, when I get a syntax error in my code, it deletes the output .css file. I thought that was fine initially. I mean, in the auto-refresh tab, the site will suddenly appear in white and Times New Roman, which couldn't make it more obvious that there's an error. Then when you correct the error and compile again, the .css file exists again. All is well, right?

Wrong. For one, I've got a few styles and CSS variables that are set on page load by JavaScript. Even when the auto-refresh refreshes properly, those often don't. I'll end up with, for example, a hero area that's not tall enough for its contents. And then I'll need to refresh.

More importantly, sometimes, the auto-refresh tab will be updated to its style-free self when the .css file stops existing, but it will not come back to its original state once it's created anew. Even manually refreshing won't fix this. Usually I get confused, thinking I still have an error and try a couple of things before realizing I wasn't doing anything wrong in my code.

When that happens, I need to hard refresh (Cmd + shift + R) to get my site back to looking normal.

Can you do something about this? I'm not sure how much is within your power and how much you absolutely cannot help, but I can see two solutions:

1. Find a way to persist the CSS file, error or not.
2. Whenever there's been a Sass error, force the CSS's refresh, cached or not.

Steps to reproduce:

1. Write some valid SCSS and compile with Dart Sass.
2. Open up an auto-refreshing tab (in Firefox, if that matters).
3. Add something invalid. For example, just type a letter alone on a line. Save.
4. Dart Sass will throw an error. The CSS file disappears. Your website is now black Times on white background.
5. Fix your error and compile. If you're (un)lucky, your website will stay black Times on white background.
6. Refresh to see no change at all.
7. Hard refresh to bring your site back to normal.
8. Sometimes, no amount of hard-refreshing will fix this. You'll just have to wait several seconds or change your style significantly enough for it to update.

**Edit: Actually no, hard refreshes do nothing. You *must* wait.**

**Comment by bdkjones** [comment]
This is going to be an issue for Dart Sass. CodeKit does not delete the existing CSS file. My hunch is that Dart Sass is deleting that file at the start of its compiling process instead of waiting to see if compiling succeeds before deleting it to replace it with a new file.

I can open an issue with them, but it will be up to the Dart Sass team to change this behavior.

**Comment by Ariane-B** [comment]
You would? That would be very nice of you.

**Comment by bdkjones** [comment]
I've opened that issue and hopefully the Dart Sass team will make the change. There's nothing I can do in CodeKit to address this, short of a REALLY hacky workaround where I copy the existing output file before calling Dart Sass and then write the old output file back into place when Dart Sass fails. That introduces overhead for compiling and is generally ugly, so I'd rather get the Dart Sass compiler to adjust its behavior if possible.

**Comment by Ariane-B** [comment]
Thanks. I appreciate it.

**Comment by bdkjones** [comment]
Following up: 

@awjin closed the Dart Sass issue because they believe the current behavior is correct. I disagree. I'll fix Dart Sass in the next CodeKit update to bring it inline with how the rest of the industry behaves.

With most Macs on SSDs and using system-level APIs to grab the data of an existing output file, restoring the contents of the output file when Dart Sass incorrectly deletes it should not introduce much noticeable overhead.

I'm reopening this issue so I can track it, since the Dart Sass team is going to leave their behavior in place.

**Comment by Ariane-B** [comment]
Thank you. I really appreciate you doing this. I went on [the issue](https://github.com/sass/dart-sass/issues/995#issuecomment-623499316) to argue further so they'll at least make that weird behaviour optional. If we're lucky, you won't have to resort to the hacky way.

**Comment by bdkjones** [comment]
Ok, I've implemented the workaround and will ship it tonight.

It's really a shame because it's literally a one-line fix in Dart's source code: https://github.com/sass/dart-sass/blob/d155f3518e92a1b41122f0f2e3b22572329c35c6/bin/sass.dart#L73

Buuuuuut, I'd rather not fork Dart Sass and keep my own custom implementation up to date, so I just have CodeKit restore the output file if Dart Sass returns an error. Hopefully the Sass team will fall in line with the rest of the industry at some point and I'll be able to remove that hack. It should not add any human-noticeable amount of time to the compiling process, although it does certainly introduce some overhead.

**Comment by Ariane-B** [comment]
Thanks. I really appreciate it.
