### ISSUE TITLE
Bundler doesn't link exported file to import file if import statement is > 1 line

### ISSUE THREAD

**Issue by matthew52pickup** [bdkjones/CodeKit#615]
When my import statement goes onto 2+ lines Codekit (and/or Rollup) no longer recognizes the link between the files.

ie.:

import { animateIn, imageLoad } from './module/animations';

is totally fine, but:

import {
    animateIn,
    imageLoad
} from './module/animations';

breaks the link.

**Comment by bdkjones** [comment]
Yep. The issue here is that CodeKit’s dependency linker does not *parse* the file when scanning; that would be obnoxiously slow. Instead, it looks for “import” and analyzes everything until the next newline. This is MUCH faster when we have to rip through every JS file in a project to link dependencies. (The semicolon is optional in JS, so we can’t rely on that as an ending delimiter.) In most cases, import statements look best and are most readable on a single line anyway.

-Bryan

**Comment by matthew52pickup** [comment]
okay thanks for clarifying! took me forever to isolate the issue but at least now I know why. I'll adjust my prettifier settings and/or import statements to keep things on one line.

**Comment by bdkjones** [comment]
Sounds good. Rollup itself should work fine; this should only affect the dependency links in CodeKit (the files that show up in the Linked Files list).
