### ISSUE TITLE
Compass projects don't uncheck Libsass checkbox.

### ISSUE THREAD

**Issue by jackw** [bdkjones/CodeKit#62]
**Quick, short summary:**
Pulled in a CK2 project which CK3 correctly recognises as a Compass project but the 'Use the Libsass compiler (recommended)' checkbox is still checked. Compilation correctly uses Ruby Sass / Compass.

**Expected results:**
The  'Use the Libsass compiler (recommended)' checkbox to be un-checked / disabled as Libsass isn't / can't be used.

**Actual results:**
The  'Use the Libsass compiler (recommended)' checkbox remains checked even though Libsass isn't being used.

**Exact steps to reproduce:**
Add a CK2 compass project to CK3.

**Your configuration (any details about your system that you think might be relevant)**
OS X El Capitan 10.11.4, CK3 Beta 3

**Comment by iox** [comment]
We have encountered a problem related to this change, after upgrading to Codekit 3:

* We have an old Rails project which is using compass for the production environment, and libsass for local development.
* Unfortunately, we can not easily upgrade to libsass for production, because that would mean upgrading a lot of dependencies. And we don't mind that the deployments take a bit longer.
* With Codekit 2, we can use libsass, even if the project is autodetected as a compass project.
* With Codekit 3, the option is grayed out, so we can't.

As a workaround, we have gone back to using Codekit 2 for now. We know this is a corner case, but we are wondering, is there any way to force Codekit 3 to use libsass?

**Comment by bdkjones** [comment]
Unfortunately, no. This is the mother of all edge cases. The only way to do what you want is to remove the `config.rb` file from the project, remove the `@import 'compass'` statement from your stylesheet and then refresh the project so CodeKit does not see it as a Compass project. Libsass will then be available.

**Comment by bdkjones** [comment]
And Libsass flat-out is not compatible with Compass. That's one of the reason's Compass has been end-of-lifed. In CodeKit 2, even though the Libsass checkbox is available, your files are being compiled with Compass and the old Ruby Sass compiler. There's no difference between 2.x and 3.x in this regard.

**Comment by iox** [comment]
Thanks for the quick response.

In Codekit 2, I strongly believe we can activate the option to use libsass. After activating it, compiling is 10 times faster. I believe that compass is only incompatible with libsass if you use the compass specific functions.

Regarding the detection of compass, this is very interesting for us, as we could modify our project locally not to be autodetected as a compass project. Could you provide a bit more information about what checks does Codekit do to autodetect Compass? I have checked and we don't have any file called `config.rb`. We are using the following though, (which is compatible with libsass - https://github.com/sass/libsass/issues/82):
```
@import compass
@import "compass/reset"
@import "compass/css3"
```

**Comment by bdkjones** [comment]
The presence of `compass` in an `@import` statement will trigger CodeKit to treat the project as a Compass project. If you're not actually *using* Compass itself, you can just pull those stylesheets out of the Compass source, drop them into your project, and import them from there. 

You could also likely drop the css3 sheet altogether and just tweak your Sass to use standard CSS3 instead of those ancient mixins. The world has come a long way.

**Comment by iox** [comment]
Thanks a lot, those are great tips ;)
