### ISSUE TITLE
[Feature Request] .codekitignore

### ISSUE THREAD

**Issue by mertasan** [bdkjones/CodeKit#633]
It would be great if we could specify files to be ignored with files like .codekitignore in the project.

We can work like .gitignore so we can markup like /folder/sub_folder

Or it can work with a logic that can ignore all the files in the folder where it is located.

It provides convenience for such a structure:

**.codekitignore**
```bash
/source/js/combine
```

## Project
```bash
├── source
│   └── js
│       ├── combine_scripts.js
│       └── combine (ignored)
│           ├── file1.js (ignored)
│           └── file2.js (ignored)
├── build
│   └── js
│       └── combine_scripts.min.js
├── .config.codekit3
└── .codekitignore
```
---
## Project
```bash
├── source
│   └── js
│       ├── combine_scripts.js
│       └── combine (ignored)
│           ├── file1.js (ignored)
│           ├── file2.js (ignored)
│           └── .codekitignore (null / ignore all files in the folder)
├── build
│   └── js
│       └── combine_scripts.min.js
└──.config.codekit3
```
---

## Contents of files

**source/js/combine/file1.js**
```js
var File1 = function () {

    var _func1 = function () {
        alert(1);
    }
    return {
        init: function () {
            _func1();
        }
    };
}();
jQuery(document).ready(function() {
    File1.init();
});
```

**source/js/combine/file2.js**
```js
var File2 = function () {

    var _func2 = function () {
        alert(2);
    }
    return {
        init: function () {
            _func2();
        }
    };
}();
jQuery(document).ready(function() {
    File2.init();
});
```

**source/js/combine_scripts.js**
```js
// @codekit-prepend "combine/file1.js";
// @codekit-prepend "combine/file2.js";
```

**Comment by bdkjones** [comment]
The trouble with this is that the whole idea behind CodeKit is that the truth lives in the app's UI. Because a Skipped Items list already exists there, introducing a second source of truth becomes opaque and complex. Folks will forget that they added something to the hidden ignore file and will be pissed off when they see something being skipped that's not in the UI's list. 

I do allow config files for Babel and ESLint, but that's because for very advanced projects they're often required. Adding that for just Skipped Items seems like overkill. What's wrong with adding that path (to the "combine" folder) to the New Project Defaults in CodeKit?
