### ISSUE TITLE
Crash on launch after update

### ISSUE THREAD

**Issue by Bangkokian** [bdkjones/CodeKit#640]
I installed the latest update on MacOS 10.14 (not sure of the CodeKit version # since I can't open CodeKit at the moment, but it's the update version that added webP images.)

The application crashes during launch.

This may be helpful:

__Application Specific Information:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSManagedObject populateFromConfigFileRepresentation:userDefaults:canonicalFallback:]: unrecognized selector sent to instance 0x60000340b200'
terminating with uncaught exception of type NSException
abort() called__

**Comment by bdkjones** [comment]
The issue is that you've allowed your Mac to get woefully out of date. If you don't want to install Big Sur (you should), at least update to the last version of Mojave: 10.14.6

Your Mac is currently vulnerable to hundreds of security issues and problems that Apple has fixed, including the bug that causes this crash.

Do not slack off on system updates.
