### ISSUE TITLE
[SASS] PostCSS warning on development environment

### ISSUE THREAD

**Issue by andremacola** [bdkjones/CodeKit#643]
**Quick, short summary:**

Using SASS with **development** environment, codekit always returns a PostCSS warning if **purgecss** or **csso** is not in use.

**Expected results:**

Compile sass in development without any warnings and PostCSS related stuff

**Exact steps to reproduce:**

Create a project with a .scss file and change the environment to developer. Here an example project: https://github.com/andremacola/codekit-postcss-warning

**Configuration (any details about your system that you think might be relevant)**

Big Sur with node v12.16.1 installed with nvm and Codekit 3.14.2

**Comment by bdkjones** [comment]
Okay, excellent. I've been able to reproduce this on my end and have already fixed it.

Node.js is releasing some critical security fixes on Tuesday, the 23rd. I'm going to hold off on pushing an update until then because I want to incorporate those fixes. This issue will be resolved in that update next week.
