### ISSUE TITLE
CodeKit slow in responsive mode in Chrome ONLY

### ISSUE THREAD

**Issue by ingalin** [bdkjones/CodeKit#702]
I have been using CodeKit for around 2 years, and this problem appeared approximately 6 months ago. 
It's very slow in the Chrome developer responsive view, taking at least 20 seconds to preview a small change in HTML or SCSS. However, it works fine if the responsive view is turned off in Chrome, and it also works fine on Firefox (with or without the responsive view). 
This issue is super annoying, and I'm wondering if there are any leads on what I could change to improve it.
BR,
Inga

**Comment by bdkjones** [comment]
This doesn't sound like CodeKit's fault, but rather Chrome's. You can try using the non-Bonjour preview address to see if Bonjour name resolution is slowing down Chrome. I'm not familiar with the emulation mode you're describing because I haven't used Chrome in years—I view it as borderline-malware at this point. It's slow, it slaughters batteries, and it eats RAM. It's the Internet Explorer of the modern age!

**Comment by bdkjones** [comment]
Also worth checking: make sure you haven't inadvertently set Chrome to simulate slow speeds. Some other guy sent me an email to complain about slow refreshes earlier today only to discover he had enabled bandwidth throttling in Chrome.

**Comment by ingalin** [comment]
Thank you @bdkjones you are a life saver! Yes, it was throttling in Chrome! Probably I pressed some key combination by mistake and turned it on as I have never changed it :)) 
it would be good if all users could agree on using only one browser :)
