### ISSUE TITLE
@Compile isn't working for js imports

### ISSUE THREAD

**Issue by heathflohre** [bdkjones/CodeKit#714]
When setting up a .kit to import and minify a js file, the build continually errors with "Compiling failed on line 62 of "index.kit": CodeKit processed the "@compile" statement successfully, but could not read the output produced at..." Using @compile on css files works as expected. This was reproduces across simple and complex js files. The build doesn't seem to be producing the compiled version of the js before importing it.

1. Create kit and js file
2. Add @compile code to kit for the js file
3. Set up build using a build folder and minifying js
4. Run the build

A test project is attached. [Archive.zip](https://github.com/user-attachments/files/16256487/Archive.zip)

**Comment by bdkjones** [comment]
Thanks, I'll take a look!

**Comment by bdkjones** [comment]
Okay, I've found the issue. It's related to the fact that JavaScript files offer two "modes" for processing: 

1. Compile
2. Check syntax only

The other languages don't have syntax checkers, which is why the bug doesn't affect them. I've fixed it for the next release. In the meantime, you can work around the issue by changing the Output Action for `test.js` to "Process" instead of "Ignore". You'll get an extra JS file in the build folder (which you can set up a Hook to delete, if you like) but it will allow the `@compile` statement to process the file.
