### ISSUE TITLE
Compile errors when using Zurb Foundation framework

### ISSUE THREAD

**Issue by didierbrouwers** [bdkjones/CodeKit#717]
**Quick, short summary:**

 Since version 6.9.0 foundation-sites uses sass-embedded. Will this package be added to Codekit in a future release?

**Expected results:**

Compile a scss file without errors.

**Actual results:**

I get the the following errors after creating a new Codekit project with the Zurb Foundation framework installed:

<img width="599" alt="afbeelding" src="https://github.com/user-attachments/assets/e9613dd9-c54b-47d9-a1dc-95b61c218d79">

**Exact steps to reproduce:**

Create a new project in Codekit and install the Zurb Foundation framework.

**Comment by bdkjones** [comment]
Embedded Sass is just a wrapper around Dart Sass. It avoids compiling Sass in JavaScript because JS is godawful slow.

Dart Sass has been part of CodeKit for a long time. It's likely that Foundation 6.9 changed the function in your screenshot (or moved it to a different spot) and the template for new projects needs to be updated. CodeKit pulls that template from a custom fork of the zurb repo, so I should be able to solve this without an app update. I'll look into it this evening.

**Comment by didierbrouwers** [comment]
It seems that color.channel() [can only be used since Dart Sass 1.79.0](https://sass-lang.com/documentation/breaking-changes/color-functions/). Codekit 3.28 uses Dart Sass 1.78.0. Could that be the cause of the errors?

**Comment by bdkjones** [comment]
Nice catch. That version of Dart Sass came out right after I updated the app three weeks ago...go figure. I've confirmed that Foundation compiles correctly with that version of Dart Sass and I'm pushing a CodeKit update now that includes it. Check for updates in about 10 minutes and you should see it.

![Screenshot 2024-10-09 at 22 01 42](https://github.com/user-attachments/assets/85a22345-40e1-4670-8d8e-5104be83e083)
