### ISSUE TITLE
Image files with PNG and WebP optimization and different output path loose settings on file change

### ISSUE THREAD

**Issue by srosenbrand** [bdkjones/CodeKit#718]
**Quick, short summary:**
All of my source files live in a /src folder containing a /webimages folder. KIT, SCSS, JS files compile as expected to my /dist folder that are on the same root level. Except images. When I overwrite an image from /src/webimages that has optimization set to PNG/JPG + webP and an output folder settings are reset to none and I need to set those again for every image I overwrite. 

**Expected results:**
I would expect the optimization settings for a file to be stored / remembered. 

**Actual results:**
Image optimization settings are reset on every overwrite from Figma or Photoshop which is time consuming and hard to remember which initial settings where set for these files.

**Exact steps to reproduce:**
1. Export image to /src/webimages, set optimization settings and set destination path. Optimize image => all goes well. 
2. Make changes to source image in Figma or Photoshop and export to /src/webimages/filename
3. Optimization settings from the initial configuration are completly lost and have to be set again and click optimize

**Your configuration (any details about your system that you think might be relevant)**

- /project
- - /dist
- - - /css
- - - /js
- - - /img (looses optimization and output path on overwrite)
- - - source-file1.kit
- - - source-file2.kit
- - - source-etc.kit

- - /src
- - - /scss
- - - /js
- - - /img
- - - compiled-file1.html
- - - compiled-file2.html
- - - compiled-etc.html
- config.codekit3

**Comment by bdkjones** [comment]
Sounds like you're tweaking optimization options in the right-hand inspector pane when a file is selected. Instead, change those options in Project Settings > Languages > [PNG | JPG | etc.].

When a new file is detected (which is what's happening when Figma blows away the old file and creates a new one), CodeKit is applying the default settings from Project Settings. To you, it seems like the image file is simply "updated" by Figma because it happens so fast, but what's actually occurring is an atomic save: the old file is deleted and replaced with the new one.

**Comment by srosenbrand** [comment]
Thanks for clarifying! Will approach compiling images this way from now on!
