### ISSUE TITLE
Image Optimization [pngquant lossy compression]

### ISSUE THREAD

**Issue by subhaze** [bdkjones/CodeKit#83]
Any thoughts on giving an option for PNG compression with pngquant. It is technically lossy, but I've used it a lot and the results are amazing on file size reduction and quality.

I was thinking this had been brought up before, but couldn't find the issue in CK2's issue tracker.

https://pngquant.org/

**Comment by bdkjones** [comment]
Yea, it's definitely not a bad idea. I'm working on image stuff now, actually. Just implemented lossy JPEG compression (#328 for details) and would like to do the same for PNG. 

I'll see if I can squeeze it into the release I'm planning for this weekend, but it may have to push to the update after that because this proximate update has some critical fixes for the stability of the Libsass compiler.

**Comment by bdkjones** [comment]
Well, I implemented pngquant just fine and it does indeed do a spectacular job. However, pngquant is not available for inclusion in closed-source projects without a commercial license. I inquired about the price of that and it's prohibitively expensive. And even then, the license is for one *exact* version and would not include updates or new releases. 

It's *possible* that you could install `pngquant` on your Mac yourself and then CodeKit could look for it in `usr/local/bin` and offer to use it if it's there. But (A) that's sloppy and violates the basic idea of CodeKit: everything you need is baked in, with no configuration and (B) it does a technically-legal but morally-dubious end run around the commercial license requirement. People deserve to be paid fairly for the software they write. It would be incredibly hypocritical for me to charge for CodeKit and then integrate the run-around for the commercial license requirement.

It's also *possible* that I could pick up the license and offer `pngquant` for an additional in-app-purchase (to recoup the license cost). I'm hesitant to do that, however, because I think most folks would just interpret that as me being greedy.

In the meantime, the only way to run pngquant with CodeKit is going to be to install it yourself and then add a Hook that runs when `*.png` files are processed. I would recommend:

`pngquant --speed=1 --quality=0-100 --strip --output $CK_OUTPUT_PATH`

I've asked the `pngquant` developer, @pornel, if there's a commercial license available for apps that aren't Enterprise scale. It's not impossible we'll be able to come to terms.

**Comment by subhaze** [comment]
Oh, ouch... Yeah I def agree option A goes against the simplicity/ideals of CodeKit, and would def open a can of worms on "you did this for X, can you also do it for Y." B, agreed as well.

For the "paid upgrade" option, I could def see where some folks probably would venture to say that, but, curious if there would be enough folks biting on that option to even make it worth the time to implement.

Sad that it's so costly to integrate, but, I'm also glad to see devs wanting to get paid for their efforts than pushing free code out 24/7 till they burn out and projects halt.

Thanks for the update!

**Comment by bdkjones** [comment]
The next update should make you pretty happy.
