### ISSUE TITLE
CodeKit using 63GB of memory

### ISSUE THREAD

**Issue by zengabor** [bdkjones/CodeKit#93]
OS X paused CodeKit 3.0 beta 5 as it was using 63GB of memory on my retina MBP 13" with 16GB of memory. 

The underlying application server (“Python” on the screenshot) stopped serving the web pages for some reason and this may have caused the memory overuse in CodeKit.

<img width="539" alt="screen shot 2016-06-12 at 10 17 53" src="https://cloud.githubusercontent.com/assets/219762/15989995/522cf0cc-3088-11e6-8125-52cf178cc2ed.png">

<img width="912" alt="screen shot 2016-06-12 at 10 18 22" src="https://cloud.githubusercontent.com/assets/219762/15989997/5fed9c20-3088-11e6-82c6-42830988e583.png">

**Comment by katerlouis** [comment]
Unfortunately I have to reopen this.
I can't score a record-breaking 68, but 16GB, which still isn't even close to normal, I suppose?

I have MAMP running in the background and just run a WP-page. 

Any ideas by now what's happening?

<img width="656" alt="5cce8554-9cef-462d-9bd8-3ecd55bd36aa" src="https://cloud.githubusercontent.com/assets/1983382/21227826/c734a622-c2db-11e6-8e89-1eca4300f2d3.png">

**Comment by bdkjones** [comment]
That's not CodeKit using that much memory; it's your page. My guess would be something's wrong with the site.

**Comment by katerlouis** [comment]
Hm– It seems only to happen when the MacBook is in rest mode? 
Strange– I'll test if it also occurs only using the mamp-address and not CodeKit's.

**Comment by katerlouis** [comment]
For whatever reason it didn't occur for a week. So I'll close it– Sorry for botherin <3

**Comment by lcpaf** [comment]
I'm also having a similar same problem here. Not really sure what is triggering this, but CodeKit uses very often more than 3GB of memory.
![screen shot 2017-02-06 at 10 22 08](https://cloud.githubusercontent.com/assets/16120452/22641568/90ff6f9c-ec57-11e6-8f32-3f93d9a1af9f.png)
I guess it never reaches higher values because I just restart the app.

**Comment by bdkjones** [comment]
Well, this is not abnormal for larger projects. People don't understand what that memory figure in Activity Monitor means. It's NOT the current amount of memory that a process is using; it's the maximum amount the OS has authorized it to use at this time. It's a "high watermark". If you have tons of big projects I CodeKit, it's possible the app might use a few GB while refreshing because it has to open files, look for dependencies, etc. The only accurate way to gauge how much RAM the app is using is to run it with Xcode's debugger tools attached. 63GB is definitely too high. That would imply some sort of infinite loop, such as a file that imports itself indirectly, etc. 3GB is "meh". I can make Xcode use 3GB without even trying hard.

**Comment by bdkjones** [comment]
Of course, high memory use combined with a beachball would be a different story. As long as performance isn't suffering, I wouldn't worry about the memory.

**Comment by lcpaf** [comment]
I totally understand your point, however, I'm not sure if 3GB is "meh". Currently I have only one project open and honestly is not that big. Sure you can easily make Xcode or phpStorm or whatever other application use lots of memory, but in this specific case, with the one project I have running on CodeKit, 3GB is definitely too much. Even phpStorm is consuming less memory than that (and that app uses way too much memory).

**Comment by lcpaf** [comment]
Regarding the memory figured in the activity monitor, I'm not really expert about that, however, I just started searching about possible CodeKit memory issues because suddenly my 16GB RAM mac 'died' due lack of memory.

**Comment by bdkjones** [comment]
Well, the first thing to do is reset the app by holding down the `option` key while launching it. Add the project back and see what the high water mark in Activity Monitor is.
